<?php

use Illuminate\Database\Seeder;
use App\Helpers\Seed;
use App\Modules\WhatWeSells\Models\WhatWeSells;

class WhatWeSellTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('what_we_sells')->truncate();

        $rows = [
            [
                'id' => 1,
                'category_id' => 2,
                'caption' => "AW TEE HONG (SINGAPOREAN, B.1932) - FISHERMEN'S JOY | SOLD FOR $19,750 SGD",
                'price_status' => 'Y',
                'title' => "Art",
                'description' => '<p>At Hotlotz we offer art from across the globe in all mediums, including: paintings; watercolours; prints and sculpture, of modern, contemporary and more traditional styles. Given our location we see a strong focus of works with a Southeast Asian connection and have a large following of collectors looking for works by Singaporean, Malaysian, Indonesian and Thai artists as well as pieces from China, Korea, Japan and further afield.</p><p><br></p><p>Recent highlights include a re-discovered work by Singaporean artist Aw Tee Hong (b.1931), unseen for 30 years, selling for $19,750 SGD; a signature ink painting by Korean artist Lee Jung Woong (b.1963) fetching $25,000 SGD; and a large work by the local artist Eng Tow (b.1947), selling for $21,500 SGD.</p><p><br></p><p><span style="font-size: 0.875rem;">Also recently offered are works by well known artists such as Rudolf Bonnet (Dutch, 1895-1978); Damien Hirst (British, b.1965); M.F.Husain (Indian, 1915-2001); Ronnie Ford (British, b.1951); Takashi Murakami (Japanese  b.1962); Yayoi Kusama (Japanese b.1929); Ismail Guglee (Pakistan, 1926-2007); Siew Hock Meng (Singaporean, b.1942) and Choo Keng Kwang (Singaporean, 1931-2019).</span><br></p><p></p>',
                'file_name' => "oKSZipWB7nAIIbbC8kGZL3if0IgsaRnQ3bWByTyJ.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/7/oKSZipWB7nAIIbbC8kGZL3if0IgsaRnQ3bWByTyJ.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_image/7/oKSZipWB7nAIIbbC8kGZL3if0IgsaRnQ3bWByTyJ.png",
                'detail_banner_file_name' => "5OW52GHOWDrg9WcSFX3eCMA93WuwLdmSAWCPFC7G.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/7/5OW52GHOWDrg9WcSFX3eCMA93WuwLdmSAWCPFC7G.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/7/5OW52GHOWDrg9WcSFX3eCMA93WuwLdmSAWCPFC7G.jpeg",
                'key_contact_1' => 4,
                'key_contact_2' => 2,
                'order' => 1,
            ],
            [
                'id' => 2,
                'category_id' => 5,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Furniture",
                'description' => "<p>At Hotlotz we strive to offer a wide and diverse range of furniture, from 19th Century and earlier antique pieces, vintage and mid-century items, through to modern and contemporary design, our focus always being on quality and condition. We also offer a good range of Chinese and Southeast Asian furniture including Peranakan and Straits Chinese pieces.</p><p><br></p><p> </p><p>Items by well known designers and manufacturers such as Philippe Starck; Kartell; B&B Italia; Ligne Roset; Le Corbusier; Charles & Ray Eames; Hans Wegner; and Herman Miller to name a few, always perform well, recently a pair of armchairs by the French designer Christian Liaigre fetching S$6,600. </p><p><br></p><p>We offer delivery and collection options through our dedicated partner to make the process of selling or buying furniture hassle free.  </p>",
                'file_name' => "bqsC8oZxfm9JyqjCPbHAZ5hgDHXFRllO4bUhN4P0.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/8/bqsC8oZxfm9JyqjCPbHAZ5hgDHXFRllO4bUhN4P0.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/8/bqsC8oZxfm9JyqjCPbHAZ5hgDHXFRllO4bUhN4P0.png",
                'detail_banner_file_name' => "ptExpeAhC4GDSKD9WNkV8um5kJ7k9SuCaZMhk5js.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/8/ptExpeAhC4GDSKD9WNkV8um5kJ7k9SuCaZMhk5js.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/8/ptExpeAhC4GDSKD9WNkV8um5kJ7k9SuCaZMhk5js.jpeg",
                'key_contact_1' => 5,
                'key_contact_2' => 2,
                'order' => 2,
            ],
            [
                'id' => 3,
                'category_id' => 7,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Home Decor",
                'description' => "<p>Hotlotz sells a wide array of antique, vintage and modern decorative items for the home. </p><p><br></p><p>Items such as table lamps; vases and bowls; trays; mirrors; baskets and lacquer; decorative sculpture; porcelain amongst others can be found throughout our regular Home & Decor sales and our Marketplace. Be it a vintage typewriter, a set of Chinese stacking boxes or an Hermes bicycle we always have an eclectic mix of items to browse through. </p>",
                'file_name' => "kBMKkeW5po3kh87EMT8JfRXqoEFNKSfCOrB5LZeh.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/10/kBMKkeW5po3kh87EMT8JfRXqoEFNKSfCOrB5LZeh.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/10/kBMKkeW5po3kh87EMT8JfRXqoEFNKSfCOrB5LZeh.png",
                'detail_banner_file_name' => "MZiNAKDFveg3LAxME9IrmGoqiCLQ6CWNscjZAuDd.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/10/MZiNAKDFveg3LAxME9IrmGoqiCLQ6CWNscjZAuDd.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/10/MZiNAKDFveg3LAxME9IrmGoqiCLQ6CWNscjZAuDd.jpeg",
                'key_contact_1' => 5,
                'key_contact_2' => 2,
                'order' => 3,
            ],
            [
                'id' => 4,
                'category_id' => 6,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Jewellery",
                'description' => "<p>Hotlotz holds regular specialist Jewellery auctions throughout the year as well as offering items within our Marketplace. Featuring a range of antique, modern and contemporary jewellery, including pieces from high end jewellers such as Cartier; Bulgari; Van Cleef & Arpels; Chopard; Pomellato and Tiffany as well as collaborations with contemporary designers and sales of loose gemstones. Recent highlights include a ruby and diamond cluster ring featuring a 3.15ct 'pigeon blood' ruby, fetching S$21,510. </p><p><br></p><p>Hotlotz was proud to partner with Far East Gemological Institute and offer a collection of certified loose gemstones, as well as offering live auctions in conjunction with the Singapore Jewellery Expo. </p><p>Hotlotz is always looking for consignments of antique or modern jewellery, be it single items or entire estates. </p><p><br></p><p>Hotlotz Pte. Ltd. is licensed to sell precious stones and precious metals in the Republic of Singapore.</p><p>Regulated Dealers Certificate of Registration no. PS20190001021</p><p></p><div><br></div><div>
</div><div><br></div><p></p>",
                'file_name' => "SrvQHW8YlzGBZbAkJZ0I57XYLwJCco4LUExct2A0.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/11/SrvQHW8YlzGBZbAkJZ0I57XYLwJCco4LUExct2A0.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_image/11/SrvQHW8YlzGBZbAkJZ0I57XYLwJCco4LUExct2A0.png",
                'detail_banner_file_name' => "w4gLHAr4XjklFerIzRg2zuSOOB3oi6rfCS3YPfOA.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/11/w4gLHAr4XjklFerIzRg2zuSOOB3oi6rfCS3YPfOA.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/11/w4gLHAr4XjklFerIzRg2zuSOOB3oi6rfCS3YPfOA.jpeg",
                'key_contact_1' => 1,
                'key_contact_2' => 6,
                'order' => 4,
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Maps & Bonds",
                'description' => "<p>Hotlotz offers antique maps across our sales platforms, within our regular monthly sales, in specialist sales and in our Marketplace. Ranging in origin and date from the 17th Century right up to the 20th Century, at various price points, and overseen by our specialist consultant.&nbsp;</p><p><br></p><p>Of particular interest are maps of Singapore, the Malay Peninsular, Southeast Asia and the Far East, however a recent highlight was a rare world map by Petrus Schenk dating to 1715, which was sold for S$4,000.</p>",
                'file_name' => "INAeFTIHt1jkSn2gfp4HdbHV6jfP0MK8xcLB3GuN.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/12/INAeFTIHt1jkSn2gfp4HdbHV6jfP0MK8xcLB3GuN.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_image/12/INAeFTIHt1jkSn2gfp4HdbHV6jfP0MK8xcLB3GuN.png",
                'detail_banner_file_name' => "hbuNIfvnVCd0OE2dUb7uRhIhF0PXmG8ornmYgU9D.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/12/hbuNIfvnVCd0OE2dUb7uRhIhF0PXmG8ornmYgU9D.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/12/hbuNIfvnVCd0OE2dUb7uRhIhF0PXmG8ornmYgU9D.jpeg",
                'key_contact_1' => 5,
                'key_contact_2' => 4,
                'order' => 5,
            ],
            [
                'id' => 6,
                'category_id' => 3,
                'caption' => "TWO ANTIQUE CHINESE 20K GOLD WEDDING BOXES | SOLD FOR $13,750 SGD",
                'price_status' => 'N',
                'title' => "Asian Collectables",
                'description' => "<p>Hotlotz is proud to offer an extensive range of Asian collectables throughout our sales calendar, featuring ceramics; jade; bronzes; silver; statues; paintings; and works of art from across the Asian region, in regular Asian Collectables and Works of Art auctions, our Home & Decor auctions, the Marketplace and in specialist single owner collections. </p><p><br></p><p>This department holds our in-house record for a single lot, in 2020, with the sale of a record-breaking Yongzheng imperial blue and white bottle vase for $6.875M SGD. In 2019/20 Hotlotz offered for sale of the single owner collection of Quek Kiok Lee, a local Singaporean collector and academic, who had amassed a vast collection across 40 years, drawing bidders from across the world.</p><p><br></p><p>The appetite for Asian ceramics and works of art continues to grow rapidly with a huge demand coming from mainland China and further afield. We are able to offer single items or entire collections and ensure they reach the largest possible audience.</p><p></p><div><br></div><p></p>",
                'file_name' => "mOIOC8b2wTdRhjgyG4Bzp6SebjV7tGDPIRdZ17uy.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/13/mOIOC8b2wTdRhjgyG4Bzp6SebjV7tGDPIRdZ17uy.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/13/mOIOC8b2wTdRhjgyG4Bzp6SebjV7tGDPIRdZ17uy.png",
                'detail_banner_file_name' => "VB0SZwc0Wbuay3Ua5KT6xyC0R26gEilSAl4JevF3.png",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/13/VB0SZwc0Wbuay3Ua5KT6xyC0R26gEilSAl4JevF3.png",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/13/VB0SZwc0Wbuay3Ua5KT6xyC0R26gEilSAl4JevF3.png",
                'key_contact_1' => 4,
                'key_contact_2' => 2,
                'order' => 6,
            ],
            [
                'id' => 7,
                'category_id' => 12,
                'caption' => "AN EMPIRE-STYLE BRASS INLAID PORTICO CLOCK | SOLD FOR $1,195 SGD",
                'price_status' => 'N',
                'title' => "Decorative Arts",
                'description' => "<p>The Decorative Arts category encompasses antique and modern European works of art, ceramics, silver, glass, clocks and other items, for example 19th Century carriage clocks, Art Nouveau bronzes, English silver, Meissen porcelain, Lladro figures; Studio and Art glass; French furniture; antique mirrors and much more. </p><p><br></p><p>Offered throughout our sales calendar and in the Marketplace, we continue to provide one of the largest ranges of European Decorative arts in Singapore, with a strong body of both local and international buyers. </p>",
                'file_name' => "iY6zifmnkGd4pbxS17MmktnHuMfJPsnudlEqZB1h.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/14/iY6zifmnkGd4pbxS17MmktnHuMfJPsnudlEqZB1h.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/14/iY6zifmnkGd4pbxS17MmktnHuMfJPsnudlEqZB1h.png",
                'detail_banner_file_name' => "FCdkCdgS9gNsfHGhjGWzIgUIlAYwIW3w2jWIheus.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/14/FCdkCdgS9gNsfHGhjGWzIgUIlAYwIW3w2jWIheus.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/14/FCdkCdgS9gNsfHGhjGWzIgUIlAYwIW3w2jWIheus.jpeg",
                'key_contact_1' => 4,
                'key_contact_2' => 2,
                'order' => 7,
            ],
            [
                'id' => 8,
                'category_id' => 4,
                'caption' => ".",
                'price_status' => 'Y',
                'title' => "Designer Fashion",
                'description' => '<p>Hotlotz offers a diverse range of designer and luxury goods across regular specialist auctions and for immediate purchase through the Hotlotz Marketplace.</p><p><br></p><p> Handbags; clothing; shoes and accessories, for both men and women, from the leading names in fashion including Hermes; Chanel; Gucci; Louis Vuitton; Dolce & Gabbana; Fendi; Christian Dior and Versace can all be found throughout our sales. A department favourite being an Hermes limited edition \'Candy Lime\' yellow Birkin handbag, realising S$8,365.</p><p><span style="font-size: 0.875rem;"><br></span></p><p><span style="font-size: 0.875rem;">Hotlotz can manage single item consignments or entire collections, recently offering for sale a single owner collection of over 400 items, including a large selection of Chanel and Dior handbags, with proceeds all to benefit local charities. </span><br></p><p><br></p><div><br></div><p></p>',
                'file_name' => "C40xgNU3nY22imRy4qZ4kzOwmXgiS96hQd95zWff.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/15/C40xgNU3nY22imRy4qZ4kzOwmXgiS96hQd95zWff.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/15/C40xgNU3nY22imRy4qZ4kzOwmXgiS96hQd95zWff.png",
                'detail_banner_file_name' => "0lSk3N5n9WY4xrh0H3r0xxDSbEI4KmjkCgzSNnMw.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/15/0lSk3N5n9WY4xrh0H3r0xxDSbEI4KmjkCgzSNnMw.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/15/0lSk3N5n9WY4xrh0H3r0xxDSbEI4KmjkCgzSNnMw.jpeg",
                'key_contact_1' => 6,
                'key_contact_2' => 5,
                'order' => 8,
            ],
            [
                'id' => 9,
                'category_id' => 8,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Rugs & Carpets",
                'description' => "<p>Hotlotz regularly offers Middle Eastern, European and Oriental rugs and carpets throughout our sales. Whether fine antique examples or modern furnishing rugs, there is always a selection available to suit all types of buyers.</p><p><br></p><p>Browse our regular Home & Decor sales or the Marketplace for the current listings. </p>",
                'file_name' => "izxHHNwp8I3pKK3ZmqiZIcBQugnQV8Voqy3Uyd76.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/16/izxHHNwp8I3pKK3ZmqiZIcBQugnQV8Voqy3Uyd76.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/16/izxHHNwp8I3pKK3ZmqiZIcBQugnQV8Voqy3Uyd76.png",
                'detail_banner_file_name' => "zCchNcWCkmFUOcOiUNbXXC7ty3iqBgYOfiYLCJhg.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/16/zCchNcWCkmFUOcOiUNbXXC7ty3iqBgYOfiYLCJhg.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/16/zCchNcWCkmFUOcOiUNbXXC7ty3iqBgYOfiYLCJhg.jpeg",
                'key_contact_1' => 5,
                'key_contact_2' => 2,
                'order' => 9,
            ],
            [
                'id' => 10,
                'category_id' => 9,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Tableware",
                'description' => "<p>Hotlotz continually offers an excellent array of tableware and associated items suitable for everyday use at home or special occasions.</p><p><br></p><p> </p><p>Crystal glassware by makers such as Baccarat, Waterford Crystal, Val St. Lambert and Lalique. </p><p>Antique and modern silver and silver-plated table services, serving dishes, candlesticks, centrepieces and bar accessories such as wine coolers and champagne buckets. </p><p>Porcelain dinner, tea and coffee services from makers such as Wedgwood, Spode, Noritake, Limoges, Royal Copenhagen amongst others. Together with other unusual and decorative pieces for entertaining and home decoration. </p><p><br></p><p>Items can be found throughout our regular Home & Decor sales and available for immediate purchase in the Marketplace.</p>",
                'file_name' => "YI33NMSY7TRS1X1r2spw9eKkbpAvY01Jh83SbIVH.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/17/YI33NMSY7TRS1X1r2spw9eKkbpAvY01Jh83SbIVH.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_image/17/YI33NMSY7TRS1X1r2spw9eKkbpAvY01Jh83SbIVH.png",
                'detail_banner_file_name' => "VbYqxUEB24B2X1VWffp1Gp6Vjw7xSrmk8BYi0iqO.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/17/VbYqxUEB24B2X1VWffp1Gp6Vjw7xSrmk8BYi0iqO.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/17/VbYqxUEB24B2X1VWffp1Gp6Vjw7xSrmk8BYi0iqO.jpeg",
                'key_contact_1' => 4,
                'key_contact_2' => 2,
                'order' => 10,
            ],
            [
                'id' => 11,
                'category_id' => 10,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Watches & Timepieces",
                'description' => "<p>Hotlotz offers good quality modern and vintage watches and timepieces across the sales calendar, within specialist auctions and in our immediate purchase Marketplace. </p><p><br></p><p>The secondary market for wristwatches has seen huge growth in recent years and the demand for examples by the best makers has never been stronger. Hotlotz regularly features examples by some of the worlds leading watch makers including Patek Philippe; Rolex; Omega; Tag Heuer; Longines and Audemars Piguet amongst others.  </p><p><br></p>",
                'file_name' => "7jdmBB8NuP92KQcmydzlOeb7DGiV7l9gjSnNVl1G.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/18/7jdmBB8NuP92KQcmydzlOeb7DGiV7l9gjSnNVl1G.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/18/7jdmBB8NuP92KQcmydzlOeb7DGiV7l9gjSnNVl1G.png",
                'detail_banner_file_name' => "pbuLRb3eo5DIOnphPf2s2i3jFmPzypgLw834NWr2.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/18/pbuLRb3eo5DIOnphPf2s2i3jFmPzypgLw834NWr2.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/18/pbuLRb3eo5DIOnphPf2s2i3jFmPzypgLw834NWr2.jpeg",
                'key_contact_1' => 1,
                'key_contact_2' => 2,
                'order' => 11,
            ],
            [
                'id' => 12,
                'category_id' => 11,
                'caption' => ".",
                'price_status' => 'N',
                'title' => "Wine & Spirits",
                'description' => "<p>In our Wine and Spirits sales Hotlotz offers a range of wine, whisky and other spirits for all budgets and tastes, whether it be investment quality French reds, ready to drink new world wines or rare bottles of Scotch single malt whisky. </p><p><br></p><p>We have the ability to offer single bottles and cases within our specialist sales, to a single owner sale of an entire wine cellar or collection. </p><p></p><div>
</div><div><br></div><div>Hotlotz Pte. Ltd. is licensed to sell liquor (Class 1A, 1B, 2A, 2B, 3A, 3B, 4) in the Republic of Singapore.</div><div>Licence number L/LL/024491/2020/P.</div><div><br></div><p></p>",
                'file_name' => "C8LiT2Y8dgfDLVxfYq1EWtkZpkvJbtrHL2RUjycx.png",
                'file_path' => "what_we_sell/main/what_we_sell_image/19/C8LiT2Y8dgfDLVxfYq1EWtkZpkvJbtrHL2RUjycx.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/main/what_we_sell_image/19/C8LiT2Y8dgfDLVxfYq1EWtkZpkvJbtrHL2RUjycx.png",
                'detail_banner_file_name' => "Fo21i2XopJF0Ha13bCcrwOHMMVssGZ1DoaOvW0aJ.jpeg",
                'detail_banner_file_path' => "what_we_sell/main/what_we_sell_banner/19/Fo21i2XopJF0Ha13bCcrwOHMMVssGZ1DoaOvW0aJ.jpeg",
                'detail_banner_full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/main/what_we_sell_banner/19/Fo21i2XopJF0Ha13bCcrwOHMMVssGZ1DoaOvW0aJ.jpeg",
                'key_contact_1' => 4,
                'key_contact_2' => 5,
                'order' => 12,
            ],
        ];

        if (count($rows) > 0) {
            Seed::insertData(WhatWeSells::class, $rows);
        }
    }
}