<?php

use Illuminate\Database\Seeder;
use App\Helpers\Seed;
use App\Modules\WhatWeSells\Models\WhatWeSellHighlight;

class WhatWeSellHighlightTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('what_we_sell_highlights')->truncate();

        $rows = [
            ## Art
            [
                'id' => 1,
                'what_we_sell_id' => 1,
                'title' => "AW TEE HONG (SINGAPOREAN, B.1932) - FISHERMEN'S JOY",
                'description' => "$19,750 SG",
                'file_name' => "4SwbFtjuW8XRddReYb8flunmSQvEnL3H7IuY5gLi.png",
                'file_path' => "what_we_sell/detail/7/1/4SwbFtjuW8XRddReYb8flunmSQvEnL3H7IuY5gLi.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/1/4SwbFtjuW8XRddReYb8flunmSQvEnL3H7IuY5gLi.png",
                'order' => 1,
            ],
            [
                'id' => 2,
                'what_we_sell_id' => 1,
                'title' => "JOHAN RUDOLF BONNET (DUTCH, 1895-1978) - PORTRAIT OF A BALINESE MAN",
                'description' => "$6,250 SGD",
                'file_name' => "t0vKuqxSRHefiCwgjjo336HZKIZNqQyVhfcceNNX.png",
                'file_path' => "what_we_sell/detail/7/2/t0vKuqxSRHefiCwgjjo336HZKIZNqQyVhfcceNNX.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/2/t0vKuqxSRHefiCwgjjo336HZKIZNqQyVhfcceNNX.png",
                'order' => 2,
            ],
            [
                'id' => 3,
                'what_we_sell_id' => 1,
                'title' => "JOHN WHIPPLE (BRITISH, 19TH CENTURY) – A RIVER LANDSCAPE",
                'description' => "$1,178 SGD",
                'file_name' => "73MojZ6DeZZDp3HcAoUfNrzZnUtSPPAgeJj8RMiU.png",
                'file_path' => "what_we_sell/detail/7/3/73MojZ6DeZZDp3HcAoUfNrzZnUtSPPAgeJj8RMiU.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/7/3/73MojZ6DeZZDp3HcAoUfNrzZnUtSPPAgeJj8RMiU.png",
                'order' => 3,
            ],
            [
                'id' => 4,
                'what_we_sell_id' => 1,
                'title' => "SIEW HOCK MENG (SINGAPOREAN, B.1942) - RECLINING NUDE",
                'description' => "$12,500 SGD",
                'file_name' => "Dy8iFNgxaHHr5VY5Guep5ihV3tW1fRWW4WFFd23j.png",
                'file_path' => "what_we_sell/detail/7/4/Dy8iFNgxaHHr5VY5Guep5ihV3tW1fRWW4WFFd23j.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/4/Dy8iFNgxaHHr5VY5Guep5ihV3tW1fRWW4WFFd23j.png",
                'order' => 4,
            ],
            [
                'id' => 5,
                'what_we_sell_id' => 1,
                'title' => "LEE JUNG WOONG (KOREAN, B.1963) - BRUSH PAINTING",
                'description' => "$25,000 SGD",
                'file_name' => "hGHgraIu56t5gFdP5RR2xyvBlpmXakbt63HDS2HL.png",
                'file_path' => "what_we_sell/detail/7/5/hGHgraIu56t5gFdP5RR2xyvBlpmXakbt63HDS2HL.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/5/hGHgraIu56t5gFdP5RR2xyvBlpmXakbt63HDS2HL.png",
                'order' => 5,
            ],
            [
                'id' => 6,
                'what_we_sell_id' => 1,
                'title' => "REN ZHEN YU (CHINESE, B.1976) - LEE KUAN YEW",
                'description' => "$2,000 SGD",
                'file_name' => "c90zW8e8C7y3qZA0fD2Nc5IJZcpeza70SXX1RWG0.jpeg",
                'file_path' => "what_we_sell/detail/7/6/c90zW8e8C7y3qZA0fD2Nc5IJZcpeza70SXX1RWG0.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/6/c90zW8e8C7y3qZA0fD2Nc5IJZcpeza70SXX1RWG0.jpeg",
                'order' => 6,
            ],
            [
                'id' => 7,
                'what_we_sell_id' => 1,
                'title' => "JAMES ELDER CHRISTIE (SCOTTISH, 1847-1914)",
                'description' => "$620 SGD",
                'file_name' => "onMgLzzY9LcublpxYOg52CfF8JEhDEWTUBkTrbkz.png",
                'file_path' => "what_we_sell/detail/7/7/onMgLzzY9LcublpxYOg52CfF8JEhDEWTUBkTrbkz.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/7/7/onMgLzzY9LcublpxYOg52CfF8JEhDEWTUBkTrbkz.png",
                'order' => 7,
            ],
            [
                'id' => 8,
                'what_we_sell_id' => 1,
                'title' => "MARC KAPLAN (FRENCH, B.1950) - VOLUPTÉ",
                'description' => "$6,000 SGD",
                'file_name' => "y5NsKoARd4TeuhKdAyD3FCMtg8XCc8auDtOIgPUR.png",
                'file_path' => "what_we_sell/detail/7/8/y5NsKoARd4TeuhKdAyD3FCMtg8XCc8auDtOIgPUR.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/8/y5NsKoARd4TeuhKdAyD3FCMtg8XCc8auDtOIgPUR.png",
                'order' => 8,
            ],
            [
                'id' => 9,
                'what_we_sell_id' => 1,
                'title' => "SOUTHEAST ASIAN SCHOOL (20TH CENTURY) - WOMEN WORKING IN A PADDY FIELD",
                'description' => "$1,060 SGD",
                'file_name' => "ms7maotL9azZSaGbOLLHRswLPJzJ0K0LVOwWKHym.png",
                'file_path' => "what_we_sell/detail/7/9/ms7maotL9azZSaGbOLLHRswLPJzJ0K0LVOwWKHym.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/9/ms7maotL9azZSaGbOLLHRswLPJzJ0K0LVOwWKHym.png",
                'order' => 9,
            ],
            [
                'id' => 10,
                'what_we_sell_id' => 1,
                'title' => "NOPARAT LIVISIDDHI (THAI, B.1932) - GREEN RICE FIELDS",
                'description' => "$1,060 SGD",
                'file_name' => "UxOOVWW1zm6dxaycBj2IvF4DczI1t4PEyU8TBQAt.png",
                'file_path' => "what_we_sell/detail/7/10/UxOOVWW1zm6dxaycBj2IvF4DczI1t4PEyU8TBQAt.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/10/UxOOVWW1zm6dxaycBj2IvF4DczI1t4PEyU8TBQAt.png",
                'order' => 10,
            ],
            [
                'id' => 11,
                'what_we_sell_id' => 1,
                'title' => "GEOFF WILLIAMS (NEW ZEALAND, B.1966) - STILL LIFE WITH EGGS",
                'description' => "$478 SGD",
                'file_name' => "o0usvW0ofQ64e57YjQD0teU7oFAVyM79vwlCACpj.png",
                'file_path' => "what_we_sell/detail/7/11/o0usvW0ofQ64e57YjQD0teU7oFAVyM79vwlCACpj.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/11/o0usvW0ofQ64e57YjQD0teU7oFAVyM79vwlCACpj.png",
                'order' => 11,
            ],
            [
                'id' => 12,
                'what_we_sell_id' => 1,
                'title' => "CHAROON BOONSUAN (THAI, B.1938) - WATER REFLECTIONS",
                'description' => "$1,125",
                'file_name' => "Xs08s3F7v3R1HPoGhq534y3H5EpGakISvH3JtUUr.png",
                'file_path' => "what_we_sell/detail/7/12/Xs08s3F7v3R1HPoGhq534y3H5EpGakISvH3JtUUr.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/7/12/Xs08s3F7v3R1HPoGhq534y3H5EpGakISvH3JtUUr.png",
                'order' => 12,
            ],
            ## Furniture
            [
                'id' => 13,
                'what_we_sell_id' => 2,
                'title' => "LIAIGRE - A SCARABEE SIDE TABLE",
                'description' => "$2,031 SGD",
                'file_name' => "LuPOD9SjpLZzHuZhdmrQennxz44Ujz9qdAxu8p1g.png",
                'file_path' => "what_we_sell/detail/8/1/LuPOD9SjpLZzHuZhdmrQennxz44Ujz9qdAxu8p1g.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/1/LuPOD9SjpLZzHuZhdmrQennxz44Ujz9qdAxu8p1g.png",
                'order' => 1,
            ],
            [
                'id' => 14,
                'what_we_sell_id' => 2,
                'title' => "B&B ITALIA - A LEATHER 'BAISITY' SOFA WITH TWO ARMCHAIRS",
                'description' => "$2,868 SGD",
                'file_name' => "g0iGj1OIIjTR7JZsgjCS00BfeaF9qJUlNcOFFJXW.png",
                'file_path' => "what_we_sell/detail/8/2/g0iGj1OIIjTR7JZsgjCS00BfeaF9qJUlNcOFFJXW.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/2/g0iGj1OIIjTR7JZsgjCS00BfeaF9qJUlNcOFFJXW.png",
                'order' => 2,
            ],
            [
                'id' => 15,
                'what_we_sell_id' => 2,
                'title' => "​A CHAISE LONGUE UPHOLSTERED WITH JIM THOMPSON FABRIC",
                'description' => "$3,107 SGD",
                'file_name' => "TvyZIHEn4IGxV1lGXDbhLuFGkdiVjo6JEWLPHCXc.png",
                'file_path' => "what_we_sell/detail/8/3/TvyZIHEn4IGxV1lGXDbhLuFGkdiVjo6JEWLPHCXc.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/3/TvyZIHEn4IGxV1lGXDbhLuFGkdiVjo6JEWLPHCXc.png",
                'order' => 3,
            ],
            [
                'id' => 16,
                'what_we_sell_id' => 2,
                'title' => "A PAIR OF 1930's BAR COUNSEL CHAIRS, FROM THE SUPREME COURT",
                'description' => "$1,135 SGD",
                'file_name' => "AsRyRloI6Mqloaks8xpWvZjdo01iciW929U2k31t.png",
                'file_path' => "what_we_sell/detail/8/4/AsRyRloI6Mqloaks8xpWvZjdo01iciW929U2k31t.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/4/AsRyRloI6Mqloaks8xpWvZjdo01iciW929U2k31t.png",
                'order' => 4,
            ],
            [
                'id' => 17,
                'what_we_sell_id' => 2,
                'title' => "CASSINA - A GLASS 'LA ROTONDA' DINING TABLE WITH SIX CHAIRS",
                'description' => "$2,150 SGD",
                'file_name' => "xPIqwIfldiueuMWYqE5yYzJsVQNq7nV3POIdimIU.png",
                'file_path' => "what_we_sell/detail/8/5/xPIqwIfldiueuMWYqE5yYzJsVQNq7nV3POIdimIU.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/5/xPIqwIfldiueuMWYqE5yYzJsVQNq7nV3POIdimIU.png",
                'order' => 5,
            ],
            [
                'id' => 18,
                'what_we_sell_id' => 2,
                'title' => "LIAIGRE - A PAIR OF ASPRE LOUNGE CHAIRS",
                'description' => "$6,692 SGD",
                'file_name' => "gGtn47Dk4hx9TwzwzkPIB1fhZ1d63EeqtvdHZMBk.png",
                'file_path' => "what_we_sell/detail/8/6/gGtn47Dk4hx9TwzwzkPIB1fhZ1d63EeqtvdHZMBk.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/6/gGtn47Dk4hx9TwzwzkPIB1fhZ1d63EeqtvdHZMBk.png",
                'order' => 6,
            ],
            [
                'id' => 19,
                'what_we_sell_id' => 2,
                'title' => "PAOLO PIVA - AN 'ALANDA' COFFEE TABLE",
                'description' => "$2,031 SGD",
                'file_name' => "nCJH8HGRn9zOoNy3GR0pIsKOrJCOjm5FzkdL60Lt.png",
                'file_path' => "what_we_sell/detail/8/7/nCJH8HGRn9zOoNy3GR0pIsKOrJCOjm5FzkdL60Lt.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/7/nCJH8HGRn9zOoNy3GR0pIsKOrJCOjm5FzkdL60Lt.png",
                'order' => 7,
            ],
            [
                'id' => 20,
                'what_we_sell_id' => 2,
                'title' => "A REPLICA LE CORBUSIER 'LC4 CHAISE LONGUE'",
                'description' => "$525 SGD",
                'file_name' => "6XMHGdfpvWc6v9mN8DYPLoHivzqhDy5MV4GO55C7.png",
                'file_path' => "what_we_sell/detail/8/8/6XMHGdfpvWc6v9mN8DYPLoHivzqhDy5MV4GO55C7.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/8/6XMHGdfpvWc6v9mN8DYPLoHivzqhDy5MV4GO55C7.png",
                'order' => 8,
            ],
            [
                'id' => 21,
                'what_we_sell_id' => 2,
                'title' => "A VINTAGE DANISH ROSEWOOD SIDEBOARD",
                'description' => "$1,314 SGD",
                'file_name' => "f5GYzKegjdnjwoOhEFIYamNcgtUCRUkTskU90uvM.png",
                'file_path' => "what_we_sell/detail/8/9/f5GYzKegjdnjwoOhEFIYamNcgtUCRUkTskU90uvM.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/9/f5GYzKegjdnjwoOhEFIYamNcgtUCRUkTskU90uvM.png",
                'order' => 9,
            ],
            [
                'id' => 22,
                'what_we_sell_id' => 2,
                'title' => "A RATTAN PLANTATION CHAISE LONGUE",
                'description' => "$286 SGD",
                'file_name' => "mLbaeBHEUra46SJ61BSB5zYsF1ARxqjolQqXAdKB.png",
                'file_path' => "what_we_sell/detail/8/10/mLbaeBHEUra46SJ61BSB5zYsF1ARxqjolQqXAdKB.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/10/mLbaeBHEUra46SJ61BSB5zYsF1ARxqjolQqXAdKB.png",
                'order' => 10,
            ],
            [
                'id' => 23,
                'what_we_sell_id' => 2,
                'title' => "A SET OF EIGHT BLUE UPHOLSTERED DINING CHAIRS",
                'description' => "$1,195 SGD",
                'file_name' => "EUaFtB8ebTrNeVSrgCkB0QgHv97H4SsYqlJ5Wzef.png",
                'file_path' => "what_we_sell/detail/8/11/EUaFtB8ebTrNeVSrgCkB0QgHv97H4SsYqlJ5Wzef.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/11/EUaFtB8ebTrNeVSrgCkB0QgHv97H4SsYqlJ5Wzef.png",
                'order' => 11,
            ],
            [
                'id' => 24,
                'what_we_sell_id' => 2,
                'title' => "A LEATHER AND MAHOGANY PORTERS CHAIR",
                'description' => "$358 SGD",
                'file_name' => "Y2lbqiVXJn78SNpHE3PzyESsziZpy1iEwqB64fVi.png",
                'file_path' => "what_we_sell/detail/8/12/Y2lbqiVXJn78SNpHE3PzyESsziZpy1iEwqB64fVi.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/8/12/Y2lbqiVXJn78SNpHE3PzyESsziZpy1iEwqB64fVi.png",
                'order' => 12,
            ],
            ## Home Decor
            [
                'id' => 25,
                'what_we_sell_id' => 3,
                'title' => "CORES DA TERRA - AN OVERSIZED CERAMIC PEAR & A CHERRY",
                'description' => "$896 SGD",
                'file_name' => "7WuYHrGWgl5JCRZuuzqsQaqqB9PxeP8GIwu03ckH.png",
                'file_path' => "what_we_sell/detail/10/1/7WuYHrGWgl5JCRZuuzqsQaqqB9PxeP8GIwu03ckH.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/1/7WuYHrGWgl5JCRZuuzqsQaqqB9PxeP8GIwu03ckH.png",
                'order' => 1,
            ],
            [
                'id' => 26,
                'what_we_sell_id' => 3,
                'title' => "A THREE DOOR SHAGREEN SIDE CABINET",
                'description' => "$2,480 SGD",
                'file_name' => "VoQ9Qr7vDqsEvxaMGjXStOKqCYH0PSLy6ss3cdoj.jpeg",
                'file_path' => "what_we_sell/detail/10/2/VoQ9Qr7vDqsEvxaMGjXStOKqCYH0PSLy6ss3cdoj.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/10/2/VoQ9Qr7vDqsEvxaMGjXStOKqCYH0PSLy6ss3cdoj.jpeg",
                'order' => 2,
            ],
            [
                'id' => 27,
                'what_we_sell_id' => 3,
                'title' => "A 'BATAVUS' BICYCLE BY HERMES",
                'description' => "$2,987 SGD",
                'file_name' => "evcSoBOVqtcfyDESPJJSE5NlzsAShSjV14KnUfnq.png",
                'file_path' => "what_we_sell/detail/10/3/evcSoBOVqtcfyDESPJJSE5NlzsAShSjV14KnUfnq.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/3/evcSoBOVqtcfyDESPJJSE5NlzsAShSjV14KnUfnq.png",
                'order' => 3,
            ],
            [
                'id' => 28,
                'what_we_sell_id' => 3,
                'title' => "VANESSA MITRANI - A RED ART GLASS VASE WITH METAL RINGS",
                'description' => "$382 SGD",
                'file_name' => "7jHxSG8po62WyEZ3TZGCkuuy2EAx6BJlFB0bSGNy.png",
                'file_path' => "what_we_sell/detail/10/4/7jHxSG8po62WyEZ3TZGCkuuy2EAx6BJlFB0bSGNy.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/4/7jHxSG8po62WyEZ3TZGCkuuy2EAx6BJlFB0bSGNy.png",
                'order' => 4,
            ],
            [
                'id' => 29,
                'what_we_sell_id' => 3,
                'title' => "A COLLECTION OF NINE MURANO ART GLASS BOTTLES",
                'description' => "$501 SGD",
                'file_name' => "zT0cUYsi6Tk31seSzorJTyJPdnpfOh8sjgqNfX64.png",
                'file_path' => "what_we_sell/detail/10/5/zT0cUYsi6Tk31seSzorJTyJPdnpfOh8sjgqNfX64.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/5/zT0cUYsi6Tk31seSzorJTyJPdnpfOh8sjgqNfX64.png",
                'order' => 5,
            ],
            [
                'id' => 30,
                'what_we_sell_id' => 3,
                'title' => "A PAIR OF GREEN LAMPS DECORATED WITH BIRDS & FLOWERS",
                'description' => "$310 SGD",
                'file_name' => "PrdH3zNXBmvtiPMQCaQ36Bt1JX1olFME9wMmedvl.png",
                'file_path' => "what_we_sell/detail/10/6/PrdH3zNXBmvtiPMQCaQ36Bt1JX1olFME9wMmedvl.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/6/PrdH3zNXBmvtiPMQCaQ36Bt1JX1olFME9wMmedvl.png",
                'order' => 6,
            ],
            [
                'id' => 31,
                'what_we_sell_id' => 3,
                'title' => "AN ACRYLIC PLATE WITH TWO PRINTS BY CHRISTIAN DEVELTER",
                'description' => "$239 SGD",
                'file_name' => "23V656YFrc2Jy5vMsaU2jZekGd1cEhur6Eb9cCQk.png",
                'file_path' => "what_we_sell/detail/10/7/23V656YFrc2Jy5vMsaU2jZekGd1cEhur6Eb9cCQk.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/7/23V656YFrc2Jy5vMsaU2jZekGd1cEhur6Eb9cCQk.png",
                'order' => 7,
            ],
            [
                'id' => 32,
                'what_we_sell_id' => 3,
                'title' => "BACCARAT - THREE GLASS HEART PAPERWEIGHTS",
                'description' => "$239 SGD",
                'file_name' => "B3t3LXSX8iqlcfFNY3aW3hRtbbWXjhnjLzu7wQOD.png",
                'file_path' => "what_we_sell/detail/10/8/B3t3LXSX8iqlcfFNY3aW3hRtbbWXjhnjLzu7wQOD.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/8/B3t3LXSX8iqlcfFNY3aW3hRtbbWXjhnjLzu7wQOD.png",
                'order' => 8,
            ],
            [
                'id' => 33,
                'what_we_sell_id' => 3,
                'title' => "A GROUP OF THREE CERAMIC TROMPE L'OEIL PAPER BAG VASES",
                'description' => "$382 SGD",
                'file_name' => "86RLY8qjryWKL0mKUywCkaSQa4DNGKSEEJoab9zp.png",
                'file_path' => "what_we_sell/detail/10/9/86RLY8qjryWKL0mKUywCkaSQa4DNGKSEEJoab9zp.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/9/86RLY8qjryWKL0mKUywCkaSQa4DNGKSEEJoab9zp.png",
                'order' => 9,
            ],
            [
                'id' => 34,
                'what_we_sell_id' => 3,
                'title' => "A PAIR OF BURMESE CARVED & LACQUERED MANUTHIHA",
                'description' => "$382 SGD",
                'file_name' => "44UontBvZ1BfRZ39AKg6B7CyYYHF976LhOelgDNZ.png",
                'file_path' => "what_we_sell/detail/10/10/44UontBvZ1BfRZ39AKg6B7CyYYHF976LhOelgDNZ.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/10/44UontBvZ1BfRZ39AKg6B7CyYYHF976LhOelgDNZ.png",
                'order' => 10,
            ],
            [
                'id' => 35,
                'what_we_sell_id' => 3,
                'title' => "FIVE VINTAGE PERANAKAN PENDANT LAMPS",
                'description' => "$382 SGD",
                'file_name' => "HcyjP8s4CXY6sGtl3h69xGbUd6F2Tmkia8UGIwYu.png",
                'file_path' => "what_we_sell/detail/10/11/HcyjP8s4CXY6sGtl3h69xGbUd6F2Tmkia8UGIwYu.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/11/HcyjP8s4CXY6sGtl3h69xGbUd6F2Tmkia8UGIwYu.png",
                'order' => 11,
            ],
            [
                'id' => 36,
                'what_we_sell_id' => 3,
                'title' => "A LACQUER AND GILT SEATED BUDDHA",
                'description' => "$239 SGD",
                'file_name' => "CRPT3v3vchkxJFIWsXYiySTVOYKo3n4YzkTcQYYL.png",
                'file_path' => "what_we_sell/detail/10/12/CRPT3v3vchkxJFIWsXYiySTVOYKo3n4YzkTcQYYL.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/10/12/CRPT3v3vchkxJFIWsXYiySTVOYKo3n4YzkTcQYYL.png",
                'order' => 12,
            ],
            ## Jewellery
            [
                'id' => 37,
                'what_we_sell_id' => 4,
                'title' => "A 3.15 CARAT BURMESE 'PIGEON'S BLOOD' RUBY AND DIAMOND RING",
                'description' => "$21,510 SGD",
                'file_name' => "Cqqs3ySGkzIilUXxez6TvTZ0DJNNqiIToqqRZRiw.png",
                'file_path' => "what_we_sell/detail/11/1/Cqqs3ySGkzIilUXxez6TvTZ0DJNNqiIToqqRZRiw.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/1/Cqqs3ySGkzIilUXxez6TvTZ0DJNNqiIToqqRZRiw.png",
                'order' => 1,
            ],
            [
                'id' => 38,
                'what_we_sell_id' => 4,
                'title' => "A BLUE SAPPHIRE SINGLE STONE RING",
                'description' => "$8,060 SGD",
                'file_name' => "l3GYbrf9Iezd6m0qEZaGSDe2B5XVkDsecA7pug8I.jpeg",
                'file_path' => "what_we_sell/detail/11/2/l3GYbrf9Iezd6m0qEZaGSDe2B5XVkDsecA7pug8I.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/2/l3GYbrf9Iezd6m0qEZaGSDe2B5XVkDsecA7pug8I.jpeg",
                'order' => 2,
            ],
            [
                'id' => 39,
                'what_we_sell_id' => 4,
                'title' => "AN EXCEPTIONAL 4.12 CARAT BLUE SAPPHIRE AND DIAMOND RING",
                'description' => "$5,736 SGD",
                'file_name' => "F3uL3AJYCEs9vaaEGw3Q0GMJ6G9uOP46IFjTnX8L.jpeg",
                'file_path' => "what_we_sell/detail/11/3/F3uL3AJYCEs9vaaEGw3Q0GMJ6G9uOP46IFjTnX8L.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/3/F3uL3AJYCEs9vaaEGw3Q0GMJ6G9uOP46IFjTnX8L.jpeg",
                'order' => 3,
            ],
            [
                'id' => 40,
                'what_we_sell_id' => 4,
                'title' => "TIFFANY & CO. - A SIGNATURE 'X' GOLD AND DIAMOND CLIP EARRING AND PENDANT SET",
                'description' => "$2,390 SGD",
                'file_name' => "fLHZVN0C2x9CVXDoUzyK90nhvbEISDmsFNPVt7mO.png",
                'file_path' => "what_we_sell/detail/11/4/fLHZVN0C2x9CVXDoUzyK90nhvbEISDmsFNPVt7mO.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/11/4/fLHZVN0C2x9CVXDoUzyK90nhvbEISDmsFNPVt7mO.png",
                'order' => 4,
            ],
            [
                'id' => 41,
                'what_we_sell_id' => 4,
                'title' => "A PLATINIUM BLUE SAPPHIRE AND DIAMOND PENDANT ON CHAIN",
                'description' => "$4,950 SGD",
                'file_name' => "wCVExBqQsBLeMZZEbOHpesObXXAYIQvrQWDlRTI5.jpeg",
                'file_path' => "what_we_sell/detail/11/5/wCVExBqQsBLeMZZEbOHpesObXXAYIQvrQWDlRTI5.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/5/wCVExBqQsBLeMZZEbOHpesObXXAYIQvrQWDlRTI5.jpeg",
                'order' => 5,
            ],
            [
                'id' => 42,
                'what_we_sell_id' => 4,
                'title' => "A PINK SAPPHIRE AND DIAMOND ETERNITY RING",
                'description' => "$2,976 SGD",
                'file_name' => "MHT3rTjA9GSi9HHlh4eEgq4M602KhxolgT6lOSXL.jpeg",
                'file_path' => "what_we_sell/detail/11/6/MHT3rTjA9GSi9HHlh4eEgq4M602KhxolgT6lOSXL.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/6/MHT3rTjA9GSi9HHlh4eEgq4M602KhxolgT6lOSXL.jpeg",
                'order' => 6,
            ],
            [
                'id' => 43,
                'what_we_sell_id' => 4,
                'title' => "A PAIR OF BLUE TOPAZ AND DIAMOND DROP EARRINGS",
                'description' => "$6,820 SGD",
                'file_name' => "RE7ZfoVu3bwXDTg35HtoeEwnlT52sI1PaWuCX4gI.jpeg",
                'file_path' => "what_we_sell/detail/11/7/RE7ZfoVu3bwXDTg35HtoeEwnlT52sI1PaWuCX4gI.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/7/RE7ZfoVu3bwXDTg35HtoeEwnlT52sI1PaWuCX4gI.jpeg",
                'order' => 7,
            ],
            [
                'id' => 44,
                'what_we_sell_id' => 4,
                'title' => "A PLATINUM RUBY AND DIAMOND RING",
                'description' => "$1,800 SGD",
                'file_name' => "5LTM8QP0BRTzd4vHQBJsjot9qJsOMA1wn8dstJOJ.jpeg",
                'file_path' => "what_we_sell/detail/11/8/5LTM8QP0BRTzd4vHQBJsjot9qJsOMA1wn8dstJOJ.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/8/5LTM8QP0BRTzd4vHQBJsjot9qJsOMA1wn8dstJOJ.jpeg",
                'order' => 8,
            ],
            [
                'id' => 45,
                'what_we_sell_id' => 4,
                'title' => "A SALTWATER TAHITIAN ROUND PEARL NECKLACE  ",
                'description' => "$1,195 SGD",
                'file_name' => "K1d0auvHfTlxzK7qm9UO418ZHegXnXdd9M4lFJJe.png",
                'file_path' => "what_we_sell/detail/11/9/K1d0auvHfTlxzK7qm9UO418ZHegXnXdd9M4lFJJe.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/11/9/K1d0auvHfTlxzK7qm9UO418ZHegXnXdd9M4lFJJe.png",
                'order' => 9,
            ],
            [
                'id' => 46,
                'what_we_sell_id' => 4,
                'title' => "AN AMETHYST CLUSTER RING & PAIR OF DROP EARRINGS",
                'description' => "$1,116 SGD",
                'file_name' => "FTnzhIpqhm6QffgYKTwCyMG3o947leJonRFtT06G.jpeg",
                'file_path' => "what_we_sell/detail/11/10/FTnzhIpqhm6QffgYKTwCyMG3o947leJonRFtT06G.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/10/FTnzhIpqhm6QffgYKTwCyMG3o947leJonRFtT06G.jpeg",
                'order' => 10,
            ],
            [
                'id' => 47,
                'what_we_sell_id' => 4,
                'title' => "A PAIR OF VINTAGE BOUCHERON 18K GOLD DROP EARRINGS",
                'description' => "$2,728 SGD",
                'file_name' => "eGbQRTesmiXdmx9a4Z6fmvQrdCOfWCtv0vvId5QJ.jpeg",
                'file_path' => "what_we_sell/detail/11/11/eGbQRTesmiXdmx9a4Z6fmvQrdCOfWCtv0vvId5QJ.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/11/eGbQRTesmiXdmx9a4Z6fmvQrdCOfWCtv0vvId5QJ.jpeg",
                'order' => 11,
            ],
            [
                'id' => 48,
                'what_we_sell_id' => 4,
                'title' => "AN EMERALD AND BLACK DIAMOND RING",
                'description' => "$1,612 SGD",
                'file_name' => "wqdTJ7VzVl7enFhhVwfcIXiDAnLaMItXJrCSPelt.jpeg",
                'file_path' => "what_we_sell/detail/11/12/wqdTJ7VzVl7enFhhVwfcIXiDAnLaMItXJrCSPelt.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/11/12/wqdTJ7VzVl7enFhhVwfcIXiDAnLaMItXJrCSPelt.jpeg",
                'order' => 12,
            ],
            ## Maps & Bonds
            [
                'id' => 49,
                'what_we_sell_id' => 5,
                'title' => "PETRUS SCHENK - A RARE DUTCH MAP OF THE WORLD (1715)",
                'description' => "$4,000 SGD",
                'file_name' => "0oXzMinYfC2d04IGyxhWcNwSsk8DyfyUvoK2dYTE.png",
                'file_path' => "what_we_sell/detail/12/1/0oXzMinYfC2d04IGyxhWcNwSsk8DyfyUvoK2dYTE.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/1/0oXzMinYfC2d04IGyxhWcNwSsk8DyfyUvoK2dYTE.png",
                'order' => 1,
            ],
            [
                'id' => 50,
                'what_we_sell_id' => 5,
                'title' => "A FRENCH MAP OF SOUTHEAST ASIA (1751)",
                'description' => "$597 SGD",
                'file_name' => "snpHnKgpWb3z3xTQtQjRmthfhATG5DIqofAlN7ju.png",
                'file_path' => "what_we_sell/detail/12/2/snpHnKgpWb3z3xTQtQjRmthfhATG5DIqofAlN7ju.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/2/snpHnKgpWb3z3xTQtQjRmthfhATG5DIqofAlN7ju.png",
                'order' => 2,
            ],
            [
                'id' => 51,
                'what_we_sell_id' => 5,
                'title' => "A DUTCH MAP OF SOUTHEAST ASIA (1635)",
                'description' => "$1,912 SGD",
                'file_name' => "9BJRWkGgW04i9qwIofUE4jVFcVglgYJNORsxdLgF.png",
                'file_path' => "what_we_sell/detail/12/3/9BJRWkGgW04i9qwIofUE4jVFcVglgYJNORsxdLgF.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/3/9BJRWkGgW04i9qwIofUE4jVFcVglgYJNORsxdLgF.png",
                'order' => 3,
            ],
            [
                'id' => 52,
                'what_we_sell_id' => 5,
                'title' => "A GERMAN MAP OF SINGAPORE (1904)",
                'description' => "$430 SGD",
                'file_name' => "4UpErwAPiHlFWMqnyEJaNpkzXvdkQQuVNIxqnZkg.png",
                'file_path' => "what_we_sell/detail/12/4/4UpErwAPiHlFWMqnyEJaNpkzXvdkQQuVNIxqnZkg.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/4/4UpErwAPiHlFWMqnyEJaNpkzXvdkQQuVNIxqnZkg.png",
                'order' => 4,
            ],
            [
                'id' => 53,
                'what_we_sell_id' => 5,
                'title' => "AN ITALIAN MAP OF ASIA (1597)",
                'description' => "$597 SGD",
                'file_name' => "kr7AaRpPArxWv2rbevgLPtjj68mKKLfjo61lmMiC.png",
                'file_path' => "what_we_sell/detail/12/5/kr7AaRpPArxWv2rbevgLPtjj68mKKLfjo61lmMiC.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/5/kr7AaRpPArxWv2rbevgLPtjj68mKKLfjo61lmMiC.png",
                'order' => 5,
            ],
            [
                'id' => 54,
                'what_we_sell_id' => 5,
                'title' => "A DUTCH MAP OF SOUTHEAST ASIA (1700)",
                'description' => "$525 SGD",
                'file_name' => "B2hlHzWEhYQxk9GnRxxfZmbN4nPfOrVwddnSoMKa.png",
                'file_path' => "what_we_sell/detail/12/6/B2hlHzWEhYQxk9GnRxxfZmbN4nPfOrVwddnSoMKa.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/6/B2hlHzWEhYQxk9GnRxxfZmbN4nPfOrVwddnSoMKa.png",
                'order' => 6,
            ],
            [
                'id' => 55,
                'what_we_sell_id' => 5,
                'title' => "A FRENCH MAP OF ASIA (1700)",
                'description' => "$597 SGD",
                'file_name' => "YEBGye62tUVAGaj6d45TKiGfYsY40dXlD3DOYRoS.png",
                'file_path' => "what_we_sell/detail/12/7/YEBGye62tUVAGaj6d45TKiGfYsY40dXlD3DOYRoS.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/7/YEBGye62tUVAGaj6d45TKiGfYsY40dXlD3DOYRoS.png",
                'order' => 7,
            ],
            [
                'id' => 56,
                'what_we_sell_id' => 5,
                'title' => "A FRENCH MAP OF EAST ASIA (1769)",
                'description' => "$430 SGD",
                'file_name' => "gomdzSqRUzYDsj9BTVVi5x8aHQWCMY3zAg8bDbPs.png",
                'file_path' => "what_we_sell/detail/12/8/gomdzSqRUzYDsj9BTVVi5x8aHQWCMY3zAg8bDbPs.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/8/gomdzSqRUzYDsj9BTVVi5x8aHQWCMY3zAg8bDbPs.png",
                'order' => 8,
            ],
            [
                'id' => 57,
                'what_we_sell_id' => 5,
                'title' => "AN AMERICAN MAP OF THE BRITISH ISLES (1937)",
                'description' => "$119 SGD",
                'file_name' => "QOYrag0r9h6CIzJxv5BCdz3UsSzz8HfjOym4qCrr.png",
                'file_path' => "what_we_sell/detail/12/9/QOYrag0r9h6CIzJxv5BCdz3UsSzz8HfjOym4qCrr.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/9/QOYrag0r9h6CIzJxv5BCdz3UsSzz8HfjOym4qCrr.png",
                'order' => 9,
            ],
            [
                'id' => 58,
                'what_we_sell_id' => 5,
                'title' => "A GERMAN MAP OF SOUTHEAST ASIA (1888)",
                'description' => "$119 SGD",
                'file_name' => "PuIVI5JVdEm5HvRo13s2nEZWL5vi2Iknwnr9JzK5.png",
                'file_path' => "what_we_sell/detail/12/10/PuIVI5JVdEm5HvRo13s2nEZWL5vi2Iknwnr9JzK5.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/10/PuIVI5JVdEm5HvRo13s2nEZWL5vi2Iknwnr9JzK5.png",
                'order' => 10,
            ],
            [
                'id' => 59,
                'what_we_sell_id' => 5,
                'title' => "A DUTCH MAP OF THE APOSTLES' TRAVELS (1714)",
                'description' => "$358 SGD",
                'file_name' => "UQRsxDYxarNltSYxPRJs4X7NMFXF1WzMst8Tm7a1.png",
                'file_path' => "what_we_sell/detail/12/11/UQRsxDYxarNltSYxPRJs4X7NMFXF1WzMst8Tm7a1.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/11/UQRsxDYxarNltSYxPRJs4X7NMFXF1WzMst8Tm7a1.png",
                'order' => 11,
            ],
            [
                'id' => 60,
                'what_we_sell_id' => 5,
                'title' => "A DUTCH MAP OF HOLY LAND (1714)",
                'description' => "$239 SGD",
                'file_name' => "9h3a6gkXS9UkSqGfBhZvm4sBCZ7cpyJCw2ONEqiI.png",
                'file_path' => "what_we_sell/detail/12/12/9h3a6gkXS9UkSqGfBhZvm4sBCZ7cpyJCw2ONEqiI.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/12/12/9h3a6gkXS9UkSqGfBhZvm4sBCZ7cpyJCw2ONEqiI.png",
                'order' => 12,
            ],
            ## Asian Collectables
            [
                'id' => 61,
                'what_we_sell_id' => 6,
                'title' => "A BLUE AND WHITE DRAGON PORCELAIN BOTTLE VASE",
                'description' => "$6,875,000 SGD",
                'file_name' => "LxqwqJrl8CVh8dTckCqt7oFN1H2o9gpXKBeAvrTD.png",
                'file_path' => "what_we_sell/detail/13/1/LxqwqJrl8CVh8dTckCqt7oFN1H2o9gpXKBeAvrTD.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/1/LxqwqJrl8CVh8dTckCqt7oFN1H2o9gpXKBeAvrTD.png",
                'order' => 1,
            ],
            [
                'id' => 62,
                'what_we_sell_id' => 6,
                'title' => "AN UNUSAL SILVER OVERLAID PORCELAIN BOWL",
                'description' => "$7,200 SGD",
                'file_name' => "nGzFaUTbYF5ZatlxKa7FGbgiUOVAZYaI9NJ67Lhe.png",
                'file_path' => "what_we_sell/detail/13/2/nGzFaUTbYF5ZatlxKa7FGbgiUOVAZYaI9NJ67Lhe.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/2/nGzFaUTbYF5ZatlxKa7FGbgiUOVAZYaI9NJ67Lhe.png",
                'order' => 2,
            ],
            [
                'id' => 63,
                'what_we_sell_id' => 6,
                'title' => "A GROUP OF TWENTY-THREE CARVED WOOD STANDS",
                'description' => "$3,968 SGD",
                'file_name' => "IhyGGEJzDzLXdfeFTgqqqkVYW1ZNCmWzDQ7qFnM8.png",
                'file_path' => "what_we_sell/detail/13/3/IhyGGEJzDzLXdfeFTgqqqkVYW1ZNCmWzDQ7qFnM8.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/13/3/IhyGGEJzDzLXdfeFTgqqqkVYW1ZNCmWzDQ7qFnM8.png",
                'order' => 3,
            ],
            [
                'id' => 64,
                'what_we_sell_id' => 6,
                'title' => "A PAIR OF 'FAMILLE ROSE' YELLOW GROUND VASES",
                'description' => "$1,800 SGD",
                'file_name' => "xa7bropyGFHwQXMnTOwDq5wwUEy5sSOlCWuqVtxX.png",
                'file_path' => "what_we_sell/detail/13/4/xa7bropyGFHwQXMnTOwDq5wwUEy5sSOlCWuqVtxX.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/4/xa7bropyGFHwQXMnTOwDq5wwUEy5sSOlCWuqVtxX.png",
                'order' => 4,
            ],
            [
                'id' => 65,
                'what_we_sell_id' => 6,
                'title' => "A TALL FLAMBÉ GLAZED MEIPING VASE",
                'description' => "$3,600 SGD",
                'file_name' => "rlN3sBeykXg4S75p1yt5pApGeo1mwNOuwZJv243A.png",
                'file_path' => "what_we_sell/detail/13/5/rlN3sBeykXg4S75p1yt5pApGeo1mwNOuwZJv243A.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/5/rlN3sBeykXg4S75p1yt5pApGeo1mwNOuwZJv243A.png",
                'order' => 5,
            ],
            [
                'id' => 66,
                'what_we_sell_id' => 6,
                'title' => "A 'CLAIR DE LUNE' GLAZED HU FORM VASE",
                'description' => "$4,080 SGD",
                'file_name' => "IDFya8fcNQxIq3J8w0hXekAlZWeqjSk3WE3dLOqw.png",
                'file_path' => "what_we_sell/detail/13/6/IDFya8fcNQxIq3J8w0hXekAlZWeqjSk3WE3dLOqw.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/6/IDFya8fcNQxIq3J8w0hXekAlZWeqjSk3WE3dLOqw.png",
                'order' => 6,
            ],
            [
                'id' => 67,
                'what_we_sell_id' => 6,
                'title' => "A LARGE SILVERY BRONZE INSCRIBED ZODIAC MIRROR",
                'description' => "$1,560 SGD",
                'file_name' => "F6ck323aRyjE3QCWZQgxq7CF7tPMCASZ0PznkZ8T.png",
                'file_path' => "what_we_sell/detail/13/7/F6ck323aRyjE3QCWZQgxq7CF7tPMCASZ0PznkZ8T.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/7/F6ck323aRyjE3QCWZQgxq7CF7tPMCASZ0PznkZ8T.png",
                'order' => 7,
            ],
            [
                'id' => 68,
                'what_we_sell_id' => 6,
                'title' => "A PAIR OF MONUMENTAL CHINESE BLUE AND WHITE PORCELAIN VASES",
                'description' => "$1,240 SGD",
                'file_name' => "fCB7SXLRK2E4eUKNjZrnvpJNaQZMY2oXf6Puapgo.jpeg",
                'file_path' => "what_we_sell/detail/13/8/fCB7SXLRK2E4eUKNjZrnvpJNaQZMY2oXf6Puapgo.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/13/8/fCB7SXLRK2E4eUKNjZrnvpJNaQZMY2oXf6Puapgo.jpeg",
                'order' => 8,
            ],
            [
                'id' => 69,
                'what_we_sell_id' => 6,
                'title' => "A 'FAMILLE ROSE' BLUE GROUND ROULEAU VASE",
                'description' => "$1,800 SGD",
                'file_name' => "FXR9wNdtH5e540LsgcyQpwAKMyMfcVCX5QEKV0El.png",
                'file_path' => "what_we_sell/detail/13/9/FXR9wNdtH5e540LsgcyQpwAKMyMfcVCX5QEKV0El.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/9/FXR9wNdtH5e540LsgcyQpwAKMyMfcVCX5QEKV0El.png",
                'order' => 9,
            ],
            [
                'id' => 70,
                'what_we_sell_id' => 6,
                'title' => "A LARGE BLUE AND WHITE PORCELAIN 'BAJIXIANG' MOON FLASK",
                'description' => "$24,000 SGD",
                'file_name' => "HFsaLPELkF4ggdk2eKkh4UrwTs0aPuI2POXljdPK.png",
                'file_path' => "what_we_sell/detail/13/10/HFsaLPELkF4ggdk2eKkh4UrwTs0aPuI2POXljdPK.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/10/HFsaLPELkF4ggdk2eKkh4UrwTs0aPuI2POXljdPK.png",
                'order' => 10,
            ],
            [
                'id' => 71,
                'what_we_sell_id' => 6,
                'title' => "TWO ANTIQUE CHINESE 20K GOLD WEDDING BOXES",
                'description' => "$13,750 SGD",
                'file_name' => "qIlVpXm6RmE5Go03AJm4Qad5QJ5q3lClGUMmEVdE.png",
                'file_path' => "what_we_sell/detail/13/11/qIlVpXm6RmE5Go03AJm4Qad5QJ5q3lClGUMmEVdE.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/11/qIlVpXm6RmE5Go03AJm4Qad5QJ5q3lClGUMmEVdE.png",
                'order' => 11,
            ],
            [
                'id' => 72,
                'what_we_sell_id' => 6,
                'title' => "A CHINESE EXPORT SILVER KETTLE ON STAND",
                'description' => "$8,750 SGD",
                'file_name' => "wjd5oGdMdwYrhXmiZzIbzvd0kwJGacqP5JuJj1GK.png",
                'file_path' => "what_we_sell/detail/13/12/wjd5oGdMdwYrhXmiZzIbzvd0kwJGacqP5JuJj1GK.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/13/12/wjd5oGdMdwYrhXmiZzIbzvd0kwJGacqP5JuJj1GK.png",
                'order' => 12,
            ],
            ## Decorative Arts
            [
                'id' => 73,
                'what_we_sell_id' => 7,
                'title' => "PRINCESS DIANA - A RARE ROYAL PRESENTATION HALCYON DAYS BOX",
                'description' => "$1,054 SGD",
                'file_name' => "J0u3igiRyk11Zmo3ehk2VVeSe7Rxrr47EuOJjatQ.jpeg",
                'file_path' => "what_we_sell/detail/14/1/J0u3igiRyk11Zmo3ehk2VVeSe7Rxrr47EuOJjatQ.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/14/1/J0u3igiRyk11Zmo3ehk2VVeSe7Rxrr47EuOJjatQ.jpeg",
                'order' => 1,
            ],
            [
                'id' => 74,
                'what_we_sell_id' => 7,
                'title' => "A BRONZE FIGURAL TABLE LAMP, IN THE ART NOUVEAU STYLE",
                'description' => "$776 SGD",
                'file_name' => "hEDE9W9WvVm1Hqa48c4kQB5ohZXz9Lk82AjD1b1G.png",
                'file_path' => "what_we_sell/detail/14/2/hEDE9W9WvVm1Hqa48c4kQB5ohZXz9Lk82AjD1b1G.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/2/hEDE9W9WvVm1Hqa48c4kQB5ohZXz9Lk82AjD1b1G.png",
                'order' => 2,
            ],
            [
                'id' => 75,
                'what_we_sell_id' => 7,
                'title' => "AN ANTIQUE FRENCH FIGURAL PATINATED SPELTER CLOCK",
                'description' => "$1,240 SGD",
                'file_name' => "ENGJeFcZRXiWppyxKWYWvFhV7J9dgV4WZ6igPOrm.png",
                'file_path' => "what_we_sell/detail/14/3/ENGJeFcZRXiWppyxKWYWvFhV7J9dgV4WZ6igPOrm.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/14/3/ENGJeFcZRXiWppyxKWYWvFhV7J9dgV4WZ6igPOrm.png",
                'order' => 3,
            ],
            [
                'id' => 76,
                'what_we_sell_id' => 7,
                'title' => "AN ANTIQUE FRENCH 'DIRECTOIRE' MAHOGANY COMMODE",
                'description' => "$1,196 SGD",
                'file_name' => "a3ntczFMQHbeDFzXAHXDHH9xsanZOcdLLCrMg2lW.png",
                'file_path' => "what_we_sell/detail/14/4/a3ntczFMQHbeDFzXAHXDHH9xsanZOcdLLCrMg2lW.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/4/a3ntczFMQHbeDFzXAHXDHH9xsanZOcdLLCrMg2lW.png",
                'order' => 4,
            ],
            [
                'id' => 77,
                'what_we_sell_id' => 7,
                'title' => "THREE SWAROVSKI 'PARADISE BIRDS'",
                'description' => "$4,464 SGD",
                'file_name' => "PzUESoKzaUJGbRz5d8j7e0YOPuNXHbf9p2YAK9QO.jpeg",
                'file_path' => "what_we_sell/detail/14/5/PzUESoKzaUJGbRz5d8j7e0YOPuNXHbf9p2YAK9QO.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/14/5/PzUESoKzaUJGbRz5d8j7e0YOPuNXHbf9p2YAK9QO.jpeg",
                'order' => 5,
            ],
            [
                'id' => 78,
                'what_we_sell_id' => 7,
                'title' => "A 19TH CENTURY FRENCH BRONZE MIRROR",
                'description' => "$286 SGD",
                'file_name' => "nsgGjRbfhakZeNIcEqOXXHAOKoTsT19oidxBcYO4.png",
                'file_path' => "what_we_sell/detail/14/6/nsgGjRbfhakZeNIcEqOXXHAOKoTsT19oidxBcYO4.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/6/nsgGjRbfhakZeNIcEqOXXHAOKoTsT19oidxBcYO4.png",
                'order' => 6,
            ],
            [
                'id' => 79,
                'what_we_sell_id' => 7,
                'title' => "A VINTAGE SILVER AND MARBLE RENAISSANCE-STYLE CHESSBOARD",
                'description' => "$1,196 SGD",
                'file_name' => "6g0GLE2ZkFFlUmQpqjAXJpH9oLDXhC6b8xwrP9S0.png",
                'file_path' => "what_we_sell/detail/14/7/6g0GLE2ZkFFlUmQpqjAXJpH9oLDXhC6b8xwrP9S0.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/7/6g0GLE2ZkFFlUmQpqjAXJpH9oLDXhC6b8xwrP9S0.png",
                'order' => 7,
            ],
            [
                'id' => 80,
                'what_we_sell_id' => 7,
                'title' => "A FRENCH PEDESTAL WOOD TABLE WITH A MARBLE TOP",
                'description' => "$215 SGD",
                'file_name' => "NyEwdtgyzatSKsxlCgWakIsgweij4iCmyj9lXrY1.png",
                'file_path' => "what_we_sell/detail/14/8/NyEwdtgyzatSKsxlCgWakIsgweij4iCmyj9lXrY1.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/8/NyEwdtgyzatSKsxlCgWakIsgweij4iCmyj9lXrY1.png",
                'order' => 8,
            ],
            [
                'id' => 81,
                'what_we_sell_id' => 7,
                'title' => "A PAIR OF ANTIQUE ORMOLU MOUNTED CANDLESTICKS",
                'description' => "$167 SGD",
                'file_name' => "zTRc39TSLOOf9PqICb3HzIxfppZGUhR1gftoRihN.png",
                'file_path' => "what_we_sell/detail/14/9/zTRc39TSLOOf9PqICb3HzIxfppZGUhR1gftoRihN.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/9/zTRc39TSLOOf9PqICb3HzIxfppZGUhR1gftoRihN.png",
                'order' => 9,
            ],
            [
                'id' => 82,
                'what_we_sell_id' => 7,
                'title' => "A SET OF SILVER FRUITS AND NUTS, IN A BOWL",
                'description' => "$597 SGD",
                'file_name' => "iTok2IhDgDnHD0JoxdCIJpMDvGjHRdH8hXS3mOO1.png",
                'file_path' => "what_we_sell/detail/14/10/iTok2IhDgDnHD0JoxdCIJpMDvGjHRdH8hXS3mOO1.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/10/iTok2IhDgDnHD0JoxdCIJpMDvGjHRdH8hXS3mOO1.png",
                'order' => 10,
            ],
            [
                'id' => 83,
                'what_we_sell_id' => 7,
                'title' => "LLADRO - A LIMITED EDITION PORCELAIN FIGURE 'DANCE'",
                'description' => "$717 SGD",
                'file_name' => "3jO20QYBVU0zgU91qLlAc4Ig0t6PUEt1Wrd2pcEg.png",
                'file_path' => "what_we_sell/detail/14/11/3jO20QYBVU0zgU91qLlAc4Ig0t6PUEt1Wrd2pcEg.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/11/3jO20QYBVU0zgU91qLlAc4Ig0t6PUEt1Wrd2pcEg.png",
                'order' => 11,
            ],
            [
                'id' => 84,
                'what_we_sell_id' => 7,
                'title' => "AN ANTIQUE FRENCH-STYLE ‘LOUIS XVI’ BUREAU",
                'description' => "$2,629 SGD",
                'file_name' => "BD1rQOCPd8OpAlRR1uX3D8ZyuvkpE1VQEXOWES0J.png",
                'file_path' => "what_we_sell/detail/14/12/BD1rQOCPd8OpAlRR1uX3D8ZyuvkpE1VQEXOWES0J.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/14/12/BD1rQOCPd8OpAlRR1uX3D8ZyuvkpE1VQEXOWES0J.png",
                'order' => 12,
            ],
            ## Designer Fashion
            [
                'id' => 85,
                'what_we_sell_id' => 8,
                'title' => "A CHRISTIAN DIOR WHITE FLOWER EMBELLISHED MINI LADY DIOR",
                'description' => "$4,464 SGD",
                'file_name' => "l0Zx1kAIa67CZgMQMerm0CktaBVhe3OiI2GdjJAt.jpeg",
                'file_path' => "what_we_sell/detail/15/1/l0Zx1kAIa67CZgMQMerm0CktaBVhe3OiI2GdjJAt.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/15/1/l0Zx1kAIa67CZgMQMerm0CktaBVhe3OiI2GdjJAt.jpeg",
                'order' => 1,
            ],
            [
                'id' => 86,
                'what_we_sell_id' => 8,
                'title' => "A PAIR OF DOLCE & GABBANA 'CARRETTO' SUNGLASSES",
                'description' => "$1,054 SGD",
                'file_name' => "0HBa5PjTfHk1QVClhRXbwSqLuZpnkm4iuuHgkWUI.jpeg",
                'file_path' => "what_we_sell/detail/15/2/0HBa5PjTfHk1QVClhRXbwSqLuZpnkm4iuuHgkWUI.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/15/2/0HBa5PjTfHk1QVClhRXbwSqLuZpnkm4iuuHgkWUI.jpeg",
                'order' => 2,
            ],
            [
                'id' => 87,
                'what_we_sell_id' => 8,
                'title' => "A CHANEL YELLOW LEATHER QUILTED SMALL BOY FLAP",
                'description' => "$4,960 SGD",
                'file_name' => "nScE3Iqbq3BrYoJj2kNEFryUPnpsfMmNydJEvKGt.jpeg",
                'file_path' => "what_we_sell/detail/15/3/nScE3Iqbq3BrYoJj2kNEFryUPnpsfMmNydJEvKGt.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/15/3/nScE3Iqbq3BrYoJj2kNEFryUPnpsfMmNydJEvKGt.jpeg",
                'order' => 3,
            ],
            [
                'id' => 88,
                'what_we_sell_id' => 8,
                'title' => "CHANEL - A PAIR OF KNEE HIGH RIDING BOOTS",
                'description' => "$500 SGD",
                'file_name' => "aIb7wmr6nwpfPGrXtJ59b8BqBEsoGFHPhSB0sy5f.png",
                'file_path' => "what_we_sell/detail/15/4/aIb7wmr6nwpfPGrXtJ59b8BqBEsoGFHPhSB0sy5f.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/4/aIb7wmr6nwpfPGrXtJ59b8BqBEsoGFHPhSB0sy5f.png",
                'order' => 4,
            ],
            [
                'id' => 89,
                'what_we_sell_id' => 8,
                'title' => "HERMÈS - A SMALL HOLDALL",
                'description' => "$1,135 SGD",
                'file_name' => "QTPcMlRBOzZypsS5iJbHBT1LDXkNYGMtSWqy0L5c.png",
                'file_path' => "what_we_sell/detail/15/5/QTPcMlRBOzZypsS5iJbHBT1LDXkNYGMtSWqy0L5c.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/5/QTPcMlRBOzZypsS5iJbHBT1LDXkNYGMtSWqy0L5c.png",
                'order' => 5,
            ],
            [
                'id' => 90,
                'what_we_sell_id' => 8,
                'title' => "CHANEL - A BLACK VINTAGE FLAP HANDBAG",
                'description' => "$4,712 SGD",
                'file_name' => "Bf673HXCN0vC2u2Rf01sNchN4yrSZ3JazfPxuABQ.jpeg",
                'file_path' => "what_we_sell/detail/15/6/Bf673HXCN0vC2u2Rf01sNchN4yrSZ3JazfPxuABQ.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/15/6/Bf673HXCN0vC2u2Rf01sNchN4yrSZ3JazfPxuABQ.jpeg",
                'order' => 6,
            ],
            [
                'id' => 91,
                'what_we_sell_id' => 8,
                'title' => "HERMÈS - A 'COLLIER DU CHIEN' CUFF",
                'description' => "$956 SGD",
                'file_name' => "m5RALB6UuUW1zYZKz33iI9BD7kHBG14CbrA36L91.png",
                'file_path' => "what_we_sell/detail/15/7/m5RALB6UuUW1zYZKz33iI9BD7kHBG14CbrA36L91.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/7/m5RALB6UuUW1zYZKz33iI9BD7kHBG14CbrA36L91.png",
                'order' => 7,
            ],
            [
                'id' => 92,
                'what_we_sell_id' => 8,
                'title' => "GUCCI - A BLACK PATENT VINTAGE LEATHER SHOULDER BAG",
                'description' => "$1,015 SGD",
                'file_name' => "XmcNI1QScmI1RijypdvL2EZPd8UUFQNG9oSsJtFF.png",
                'file_path' => "what_we_sell/detail/15/8/XmcNI1QScmI1RijypdvL2EZPd8UUFQNG9oSsJtFF.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/8/XmcNI1QScmI1RijypdvL2EZPd8UUFQNG9oSsJtFF.png",
                'order' => 8,
            ],
            [
                'id' => 93,
                'what_we_sell_id' => 8,
                'title' => "HERMÈS - A PAIR OF 'JUMPING' RED SUEDE HIGH BOOTS",
                'description' => "$478 SGD",
                'file_name' => "9yLiRYUMNTIpfVPqgzWFi9J2fuUjDM3EgKdgNpmk.png",
                'file_path' => "what_we_sell/detail/15/9/9yLiRYUMNTIpfVPqgzWFi9J2fuUjDM3EgKdgNpmk.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/9/9yLiRYUMNTIpfVPqgzWFi9J2fuUjDM3EgKdgNpmk.png",
                'order' => 9,
            ],
            [
                'id' => 94,
                'what_we_sell_id' => 8,
                'title' => "HERMÈS - A LIMITED EDITION 'CANDY LIME' YELLOW TOGO BIRKIN HANDBAG",
                'description' => "$8,365 SGD",
                'file_name' => "jVjXQxa4p4KOso7QE7y28fCkGE1BpjRtDLPL0bwC.png",
                'file_path' => "what_we_sell/detail/15/10/jVjXQxa4p4KOso7QE7y28fCkGE1BpjRtDLPL0bwC.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/10/jVjXQxa4p4KOso7QE7y28fCkGE1BpjRtDLPL0bwC.png",
                'order' => 10,
            ],
            [
                'id' => 95,
                'what_we_sell_id' => 8,
                'title' => "HERMÈS - A LACQUER CUFF",
                'description' => "$717 SGD",
                'file_name' => "urHg34lIruLMoRK8j4Py0DPyfB1yPoWBt2Ko30VD.png",
                'file_path' => "what_we_sell/detail/15/11/urHg34lIruLMoRK8j4Py0DPyfB1yPoWBt2Ko30VD.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/15/11/urHg34lIruLMoRK8j4Py0DPyfB1yPoWBt2Ko30VD.png",
                'order' => 11,
            ],
            [
                'id' => 96,
                'what_we_sell_id' => 8,
                'title' => "A DOLCE & GABBANA RED WOOL CRÊPE DAISY DRESS",
                'description' => "$558 SGD",
                'file_name' => "jYnyQKJGpfKjBB2smxK93BpdR6Rz2IedRsiyCKt2.jpeg",
                'file_path' => "what_we_sell/detail/15/12/jYnyQKJGpfKjBB2smxK93BpdR6Rz2IedRsiyCKt2.jpeg",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/15/12/jYnyQKJGpfKjBB2smxK93BpdR6Rz2IedRsiyCKt2.jpeg",
                'order' => 12,
            ],
            ## Rugs & Carpets
            [
                'id' => 97,
                'what_we_sell_id' => 9,
                'title' => "A PERSIAN KERMAN CARPET",
                'description' => "$1,075 SGD",
                'file_name' => "2Qr5ot1f6UIB6QuoRgKbkgI5k4MIUEcr5Bg3tGbO.png",
                'file_path' => "what_we_sell/detail/16/1/2Qr5ot1f6UIB6QuoRgKbkgI5k4MIUEcr5Bg3tGbO.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/1/2Qr5ot1f6UIB6QuoRgKbkgI5k4MIUEcr5Bg3tGbO.png",
                'order' => 1,
            ],
            [
                'id' => 98,
                'what_we_sell_id' => 9,
                'title' => "AN IRANIAN ZANJAN RUG",
                'description' => "$310 SGD",
                'file_name' => "qzYCpFQZYxpdZAp7vVKDymsfeVMwSse7TW1q8PCT.png",
                'file_path' => "what_we_sell/detail/16/2/qzYCpFQZYxpdZAp7vVKDymsfeVMwSse7TW1q8PCT.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/2/qzYCpFQZYxpdZAp7vVKDymsfeVMwSse7TW1q8PCT.png",
                'order' => 2,
            ],
            [
                'id' => 99,
                'what_we_sell_id' => 9,
                'title' => "A KASHMIRI SILK BLACK AND BEIGE CARPET",
                'description' => "$1,792 SGD",
                'file_name' => "o16apn5qzkzSVKhqpvcwuv40w2G5APDGrzoOokdB.png",
                'file_path' => "what_we_sell/detail/16/3/o16apn5qzkzSVKhqpvcwuv40w2G5APDGrzoOokdB.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/3/o16apn5qzkzSVKhqpvcwuv40w2G5APDGrzoOokdB.png",
                'order' => 3,
            ],
            [
                'id' => 100,
                'what_we_sell_id' => 9,
                'title' => "A KASHMIRI SILK RED FLORAL CARPET",
                'description' => "1,912 SGD",
                'file_name' => "ZKmj8SzqMmc0P5CrRBf9zrYdnNaxuY1O2JxzgsHq.png",
                'file_path' => "what_we_sell/detail/16/4/ZKmj8SzqMmc0P5CrRBf9zrYdnNaxuY1O2JxzgsHq.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/4/ZKmj8SzqMmc0P5CrRBf9zrYdnNaxuY1O2JxzgsHq.png",
                'order' => 4,
            ],
            [
                'id' => 101,
                'what_we_sell_id' => 9,
                'title' => "AN IRANIAN KHORASAN RUG",
                'description' => "$549 SGD",
                'file_name' => "G0TObHxi8xiN32frJQvbECoJlKgvTMgeePZGAmxH.png",
                'file_path' => "what_we_sell/detail/16/5/G0TObHxi8xiN32frJQvbECoJlKgvTMgeePZGAmxH.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/5/G0TObHxi8xiN32frJQvbECoJlKgvTMgeePZGAmxH.png",
                'order' => 5,
            ],
            [
                'id' => 102,
                'what_we_sell_id' => 9,
                'title' => "A KASHMIRI SILK BEIGE MEDALLION CARPET",
                'description' => "$1,792 SGD",
                'file_name' => "cVJXVfysYB8crIMcRfzQfqdowpcg6EjiVpbvZU8i.png",
                'file_path' => "what_we_sell/detail/16/6/cVJXVfysYB8crIMcRfzQfqdowpcg6EjiVpbvZU8i.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/6/cVJXVfysYB8crIMcRfzQfqdowpcg6EjiVpbvZU8i.png",
                'order' => 6,
            ],
            [
                'id' => 103,
                'what_we_sell_id' => 9,
                'title' => "AN IRANIAN CARPET, IN VERAMIN STYLE",
                'description' => "$2,390 SGD",
                'file_name' => "XQYYFiLcaXJ7d5HjbKwsHlEzSulHiomUnTUax02W.png",
                'file_path' => "what_we_sell/detail/16/7/XQYYFiLcaXJ7d5HjbKwsHlEzSulHiomUnTUax02W.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/7/XQYYFiLcaXJ7d5HjbKwsHlEzSulHiomUnTUax02W.png",
                'order' => 7,
            ],
            [
                'id' => 104,
                'what_we_sell_id' => 9,
                'title' => "AN IRANIAN SAROGH RUNNER",
                'description' => "$478 SGD",
                'file_name' => "fazePrNiHZcBnn2dojglGC75nX4xSQhiT5Oa2WP8.png",
                'file_path' => "what_we_sell/detail/16/8/fazePrNiHZcBnn2dojglGC75nX4xSQhiT5Oa2WP8.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/8/fazePrNiHZcBnn2dojglGC75nX4xSQhiT5Oa2WP8.png",
                'order' => 8,
            ],
            [
                'id' => 105,
                'what_we_sell_id' => 9,
                'title' => "AN AFGHAN PRAYER RUG",
                'description' => "$478 SGD",
                'file_name' => "BVClvSXjH7m1Yyf21SCb82ZD6ZeTVIOTv6o0Q6bS.png",
                'file_path' => "what_we_sell/detail/16/9/BVClvSXjH7m1Yyf21SCb82ZD6ZeTVIOTv6o0Q6bS.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/9/BVClvSXjH7m1Yyf21SCb82ZD6ZeTVIOTv6o0Q6bS.png",
                'order' => 9,
            ],
            [
                'id' => 106,
                'what_we_sell_id' => 9,
                'title' => "A PERSIAN QASHQAI RUNNER",
                'description' => "$382 SGD",
                'file_name' => "HFouypXs9GoHkE1hqbQHmydVv1VdOSHceOMEoTjD.png",
                'file_path' => "what_we_sell/detail/16/10/HFouypXs9GoHkE1hqbQHmydVv1VdOSHceOMEoTjD.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/10/HFouypXs9GoHkE1hqbQHmydVv1VdOSHceOMEoTjD.png",
                'order' => 10,
            ],
            [
                'id' => 107,
                'what_we_sell_id' => 9,
                'title' => "A TIBETAN CONTEMPORARY MUSTARD RUNNER",
                'description' => "$239 SGD",
                'file_name' => "YG45PhDYvrKhLNOYa35MIzLMVNY8X7FamZjuwy91.png",
                'file_path' => "what_we_sell/detail/16/11/YG45PhDYvrKhLNOYa35MIzLMVNY8X7FamZjuwy91.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/11/YG45PhDYvrKhLNOYa35MIzLMVNY8X7FamZjuwy91.png",
                'order' => 11,
            ],
            [
                'id' => 108,
                'what_we_sell_id' => 9,
                'title' => "AN ANTIQUE PRAYER RUG",
                'description' => "$358 SGD",
                'file_name' => "6cE0dR1f5dAkqVqvPaKEyzwd3ganSzaP3pLUSxom.png",
                'file_path' => "what_we_sell/detail/16/12/6cE0dR1f5dAkqVqvPaKEyzwd3ganSzaP3pLUSxom.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/16/12/6cE0dR1f5dAkqVqvPaKEyzwd3ganSzaP3pLUSxom.png",
                'order' => 12,
            ],
            ## Tableware
            [
                'id' => 109,
                'what_we_sell_id' => 10,
                'title' => "ARTISANAT DE LORRAINE - SIX CRYSTAL COLOURED WINE GLASSES",
                'description' => "$286 SGD",
                'file_name' => "7lY50kioGxgikGDS21ns6UED19tRJueJ3Xnh5CjV.png",
                'file_path' => "what_we_sell/detail/17/1/7lY50kioGxgikGDS21ns6UED19tRJueJ3Xnh5CjV.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/1/7lY50kioGxgikGDS21ns6UED19tRJueJ3Xnh5CjV.png",
                'order' => 1,
            ],
            [
                'id' => 110,
                'what_we_sell_id' => 10,
                'title' => "CHRISTIAN DIOR - A FULL CANTEEN FOR TWELVE",
                'description' => "$3,585 SGD",
                'file_name' => "HvulbE41yMbpxN49fZ1jz4lePvHGRCaw1f4uRClX.png",
                'file_path' => "what_we_sell/detail/17/2/HvulbE41yMbpxN49fZ1jz4lePvHGRCaw1f4uRClX.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/2/HvulbE41yMbpxN49fZ1jz4lePvHGRCaw1f4uRClX.png",
                'order' => 2,
            ],
            [
                'id' => 111,
                'what_we_sell_id' => 10,
                'title' => "VAL SAINT LAMBERT - A RED FLASHED AND CUT GLASS PEDESTAL BOWL",
                'description' => "$167 SGD",
                'file_name' => "jENCysauMoUSOkAv2Rr2dn1JainaGmaf9KWARIl3.png",
                'file_path' => "what_we_sell/detail/17/3/jENCysauMoUSOkAv2Rr2dn1JainaGmaf9KWARIl3.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/3/jENCysauMoUSOkAv2Rr2dn1JainaGmaf9KWARIl3.png",
                'order' => 3,
            ],
            [
                'id' => 112,
                'what_we_sell_id' => 10,
                'title' => "A ROYAL COPENHAGEN BLUE AND WHITE PORCELAIN SOUP TUREEN, COVER AND STAND",
                'description' => "$215 SGD",
                'file_name' => "4yV0kBgE3CRksIRAwjtE7bKW0cbNcZQ8bEHLOLI0.png",
                'file_path' => "what_we_sell/detail/17/4/4yV0kBgE3CRksIRAwjtE7bKW0cbNcZQ8bEHLOLI0.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/4/4yV0kBgE3CRksIRAwjtE7bKW0cbNcZQ8bEHLOLI0.png",
                'order' => 4,
            ],
            [
                'id' => 113,
                'what_we_sell_id' => 10,
                'title' => "A SET OF EIGHTEEN VINTAGE SILVERPLATED KNIFE RESTS",
                'description' => "$95 SGD",
                'file_name' => "2gNsS7DmoM04RHkgnVHqJOemrJBCsJuJNHqRjgty.png",
                'file_path' => "what_we_sell/detail/17/5/2gNsS7DmoM04RHkgnVHqJOemrJBCsJuJNHqRjgty.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/5/2gNsS7DmoM04RHkgnVHqJOemrJBCsJuJNHqRjgty.png",
                'order' => 5,
            ],
            [
                'id' => 114,
                'what_we_sell_id' => 10,
                'title' => "NORITAKE - A PORCELAIN DINNER SERVICE FOR THIRTY",
                'description' => "$1,075 SGD",
                'file_name' => "jY6lX0rIrp8AsY7qThRTegYENatajoLGNcwRCCUl.png",
                'file_path' => "what_we_sell/detail/17/6/jY6lX0rIrp8AsY7qThRTegYENatajoLGNcwRCCUl.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/6/jY6lX0rIrp8AsY7qThRTegYENatajoLGNcwRCCUl.png",
                'order' => 6,
            ],
            [
                'id' => 115,
                'what_we_sell_id' => 10,
                'title' => "SPODE - AN EXTENSIVE 'TUSCANA' DINNER SERVICE",
                'description' => "$896 SGD",
                'file_name' => "Tk9Y2LejVIttE01DdiKU6XkPnK7NSXSMJicqm3Ne.png",
                'file_path' => "what_we_sell/detail/17/7/Tk9Y2LejVIttE01DdiKU6XkPnK7NSXSMJicqm3Ne.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/7/Tk9Y2LejVIttE01DdiKU6XkPnK7NSXSMJicqm3Ne.png",
                'order' => 7,
            ],
            [
                'id' => 116,
                'what_we_sell_id' => 10,
                'title' => "HERMÈS - A 'BALCON DU GUADALQUIVIR' PORCELAIN PART DINNER SERVICE",
                'description' => "$2,031 SGD",
                'file_name' => "aJAONBVUeCQAPod0d2QNwgfymniv6vlhFGNMwpFB.png",
                'file_path' => "what_we_sell/detail/17/8/aJAONBVUeCQAPod0d2QNwgfymniv6vlhFGNMwpFB.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/8/aJAONBVUeCQAPod0d2QNwgfymniv6vlhFGNMwpFB.png",
                'order' => 8,
            ],
            [
                'id' => 117,
                'what_we_sell_id' => 10,
                'title' => "CHRISTOFLE - A SILVER PLATED WINE BUCKET",
                'description' => "$334 SGD",
                'file_name' => "u7XmwKsWoNpNWXAIXrQbyhMPaNcrigJNthuaSgio.png",
                'file_path' => "what_we_sell/detail/17/9/u7XmwKsWoNpNWXAIXrQbyhMPaNcrigJNthuaSgio.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/9/u7XmwKsWoNpNWXAIXrQbyhMPaNcrigJNthuaSgio.png",
                'order' => 9,
            ],
            [
                'id' => 118,
                'what_we_sell_id' => 10,
                'title' => "A PART SERVICE OF EUROPEAN SILVER FLATWARE",
                'description' => "$1,488 SGD",
                'file_name' => "5adDvA5UUg834LFYxQVTDAtvDG8LOQirmYkkrW99.png",
                'file_path' => "what_we_sell/detail/17/10/5adDvA5UUg834LFYxQVTDAtvDG8LOQirmYkkrW99.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/17/10/5adDvA5UUg834LFYxQVTDAtvDG8LOQirmYkkrW99.png",
                'order' => 10,
            ],
            [
                'id' => 119,
                'what_we_sell_id' => 10,
                'title' => "ORREFORS SWEDEN - A CLEAR CHAMPAGNE BUCKET",
                'description' => "$191 SGD",
                'file_name' => "xIjOaIllSQM4QyNHzrp817ELt5oPapH7QaRWsiRk.png",
                'file_path' => "what_we_sell/detail/17/11/xIjOaIllSQM4QyNHzrp817ELt5oPapH7QaRWsiRk.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/11/xIjOaIllSQM4QyNHzrp817ELt5oPapH7QaRWsiRk.png",
                'order' => 11,
            ],
            [
                'id' => 120,
                'what_we_sell_id' => 10,
                'title' => "FOUR MID-CENTURY CHAMPAGNE COUPES",
                'description' => "$120 SGD",
                'file_name' => "rP0PFXYbKzf1KLgC4AziY5qocH0Raa2IEPYRstnu.png",
                'file_path' => "what_we_sell/detail/17/12/rP0PFXYbKzf1KLgC4AziY5qocH0Raa2IEPYRstnu.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/17/12/rP0PFXYbKzf1KLgC4AziY5qocH0Raa2IEPYRstnu.png",
                'order' => 12,
            ],
            ## Watches & Timepieces
            [
                'id' => 121,
                'what_we_sell_id' => 11,
                'title' => "ROLEX - A VINTAGE SEA-DWELLER CHRONOMETER",
                'description' => "$11,352 SGD",
                'file_name' => "N30dUy8rfjBUliS4VJTznCEJziKYHf5S4s2Le3oy.png",
                'file_path' => "what_we_sell/detail/18/1/N30dUy8rfjBUliS4VJTznCEJziKYHf5S4s2Le3oy.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/1/N30dUy8rfjBUliS4VJTznCEJziKYHf5S4s2Le3oy.png",
                'order' => 1,
            ],
            [
                'id' => 122,
                'what_we_sell_id' => 11,
                'title' => "AN 18K GOLD PATEK PHILIPPE  CALATRAVA WRISTWATCH",
                'description' => "$14,880 SGD",
                'file_name' => "ly3KO0a8AoY0lhCzxEn4DVHRHgSPR2acCtXPMisV.png",
                'file_path' => "what_we_sell/detail/18/2/ly3KO0a8AoY0lhCzxEn4DVHRHgSPR2acCtXPMisV.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/production.hotlotz.com/public/what_we_sell/detail/18/2/ly3KO0a8AoY0lhCzxEn4DVHRHgSPR2acCtXPMisV.png",
                'order' => 2,
            ],
            [
                'id' => 123,
                'what_we_sell_id' => 11,
                'title' => "OMEGA - A VINTAGE 'CONSTELLATION' WATCH",
                'description' => "$1,792 SGD",
                'file_name' => "EZJaO73zg0gvXIoJg45o6iIxPmjvsWo98WszPUHA.png",
                'file_path' => "what_we_sell/detail/18/3/EZJaO73zg0gvXIoJg45o6iIxPmjvsWo98WszPUHA.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/3/EZJaO73zg0gvXIoJg45o6iIxPmjvsWo98WszPUHA.png",
                'order' => 3,
            ],
            [
                'id' => 124,
                'what_we_sell_id' => 11,
                'title' => "TAG HEUER - A LIMITED EDITION MONACO WATCH",
                'description' => "$3,824 SGD",
                'file_name' => "e3oFuGHe8ZncUeTc1qOZvKQWEp5vlIDO5MCcYFzX.png",
                'file_path' => "what_we_sell/detail/18/4/e3oFuGHe8ZncUeTc1qOZvKQWEp5vlIDO5MCcYFzX.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/4/e3oFuGHe8ZncUeTc1qOZvKQWEp5vlIDO5MCcYFzX.png",
                'order' => 4,
            ],
            [
                'id' => 125,
                'what_we_sell_id' => 11,
                'title' => "ROLEX - A VINTAGE 'OYSTER PERPETUAL' DATEJUST LADIES WATCH",
                'description' => "$8,365 SGD",
                'file_name' => "9d7ZkzgDaPhFaj9RAbTTShQwOD2SOjAZvRVmDuHH.png",
                'file_path' => "what_we_sell/detail/18/5/9d7ZkzgDaPhFaj9RAbTTShQwOD2SOjAZvRVmDuHH.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/5/9d7ZkzgDaPhFaj9RAbTTShQwOD2SOjAZvRVmDuHH.png",
                'order' => 5,
            ],
            [
                'id' => 126,
                'what_we_sell_id' => 11,
                'title' => "MONTBLANC - A 'NICOLAS RIEUSSEC' WATCH",
                'description' => "$3,585 SGD",
                'file_name' => "QAwHcYynymb3FlqGso9POsKMXlJaEIVAsSZbfqT1.png",
                'file_path' => "what_we_sell/detail/18/6/QAwHcYynymb3FlqGso9POsKMXlJaEIVAsSZbfqT1.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/6/QAwHcYynymb3FlqGso9POsKMXlJaEIVAsSZbfqT1.png",
                'order' => 6,
            ],
            [
                'id' => 127,
                'what_we_sell_id' => 11,
                'title' => "ROLEX - AN 'OYSTER PERPETUAL' DATEJUST WATCH",
                'description' => "$4,660 SGD",
                'file_name' => "jZ0G4HZd6clDuwrrtmANYRsrgTD8bUpACPeYAyln.png",
                'file_path' => "what_we_sell/detail/18/7/jZ0G4HZd6clDuwrrtmANYRsrgTD8bUpACPeYAyln.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/7/jZ0G4HZd6clDuwrrtmANYRsrgTD8bUpACPeYAyln.png",
                'order' => 7,
            ],
            [
                'id' => 128,
                'what_we_sell_id' => 11,
                'title' => "AN ANTIQUE ENGLISH SILVER POCKET WATCH",
                'description' => "$358 SGD",
                'file_name' => "CKe41547aYdDXH38iTXPUReEYUvxRXwVph9pUTAS.png",
                'file_path' => "what_we_sell/detail/18/8/CKe41547aYdDXH38iTXPUReEYUvxRXwVph9pUTAS.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/8/CKe41547aYdDXH38iTXPUReEYUvxRXwVph9pUTAS.png",
                'order' => 8,
            ],
            [
                'id' => 129,
                'what_we_sell_id' => 11,
                'title' => "LONGINES - AN 'EVIDENZA' WATCH",
                'description' => "$2,749 SGD",
                'file_name' => "tGN2F45Ja7BpthAZ3vKRH3zZ67Y2b4vVYkzeRqzo.png",
                'file_path' => "what_we_sell/detail/18/9/tGN2F45Ja7BpthAZ3vKRH3zZ67Y2b4vVYkzeRqzo.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/9/tGN2F45Ja7BpthAZ3vKRH3zZ67Y2b4vVYkzeRqzo.png",
                'order' => 9,
            ],
            [
                'id' => 130,
                'what_we_sell_id' => 11,
                'title' => "CARTIER - AN 18K WHITE GOLD 'BAIGNOIRE' LADIES WATCH",
                'description' => "$5,975 SGD",
                'file_name' => "wJBnNHFbzXKyauBHANNhdqfnJZx6WHDDq1DMckRg.png",
                'file_path' => "what_we_sell/detail/18/10/wJBnNHFbzXKyauBHANNhdqfnJZx6WHDDq1DMckRg.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/10/wJBnNHFbzXKyauBHANNhdqfnJZx6WHDDq1DMckRg.png",
                'order' => 10,
            ],
            [
                'id' => 131,
                'what_we_sell_id' => 11,
                'title' => "LOUIS VUITTON - A PINK 'TAMBOUR' LADIES WATCH",
                'description' => "$573 SGD",
                'file_name' => "pK8gq4J0zzamWXzx8OuuiQXR9EqC8F7TRwWeEkuz.png",
                'file_path' => "what_we_sell/detail/18/11/pK8gq4J0zzamWXzx8OuuiQXR9EqC8F7TRwWeEkuz.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/11/pK8gq4J0zzamWXzx8OuuiQXR9EqC8F7TRwWeEkuz.png",
                'order' => 11,
            ],
            [
                'id' => 132,
                'what_we_sell_id' => 11,
                'title' => "OMEGA - A 'SEAMASTER' AUTOMATIC WATCH",
                'description' => "$597 SGD",
                'file_name' => "GVPvSUwsd8XwjqSvReeWnO4p8wJUxOxm1h3ileLY.png",
                'file_path' => "what_we_sell/detail/18/12/GVPvSUwsd8XwjqSvReeWnO4p8wJUxOxm1h3ileLY.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/18/12/GVPvSUwsd8XwjqSvReeWnO4p8wJUxOxm1h3ileLY.png",
                'order' => 12,
            ],
            ## Wine & Spirits
            [
                'id' => 133,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU TALBOT, 2005",
                'description' => "$358 SGD",
                'file_name' => "4AVKbrKjCiNRyy6RyPL6D5vVXbgJRjLwMHp4eHJ6.png",
                'file_path' => "what_we_sell/detail/19/1/4AVKbrKjCiNRyy6RyPL6D5vVXbgJRjLwMHp4eHJ6.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/1/4AVKbrKjCiNRyy6RyPL6D5vVXbgJRjLwMHp4eHJ6.png",
                'order' => 1,
            ],
            [
                'id' => 134,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU DOMAINE DE CHEVALIER, 2005",
                'description' => "$358 SGD",
                'file_name' => "rCjwZy2EvLIBFMypaABfITRL8MPWYDRS9i3ZzG7r.png",
                'file_path' => "what_we_sell/detail/19/2/rCjwZy2EvLIBFMypaABfITRL8MPWYDRS9i3ZzG7r.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/2/rCjwZy2EvLIBFMypaABfITRL8MPWYDRS9i3ZzG7r.png",
                'order' => 2,
            ],
            [
                'id' => 135,
                'what_we_sell_id' => 12,
                'title' => "THREE BOTTLES OF CHATEAU DE HAUT BRION BLANC, 1988",
                'description' => "$1,195 SGD",
                'file_name' => "60qyYFq0UeE36E1dxlhn7g2Vwxb5OcLpoy1Ekvnl.png",
                'file_path' => "what_we_sell/detail/19/3/60qyYFq0UeE36E1dxlhn7g2Vwxb5OcLpoy1Ekvnl.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/3/60qyYFq0UeE36E1dxlhn7g2Vwxb5OcLpoy1Ekvnl.png",
                'order' => 3,
            ],
            [
                'id' => 136,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU L'ENCLOS, 2005",
                'description' => "$239 SGD",
                'file_name' => "IxAQszGJUyECr9p0EHMwvXhpc9l8TPvm64j99uM5.png",
                'file_path' => "what_we_sell/detail/19/4/IxAQszGJUyECr9p0EHMwvXhpc9l8TPvm64j99uM5.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/4/IxAQszGJUyECr9p0EHMwvXhpc9l8TPvm64j99uM5.png",
                'order' => 4,
            ],
            [
                'id' => 137,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU CALON SEGUR, 2005",
                'description' => "$478 SGD",
                'file_name' => "XZeGVO3HsWHzyGfARombF8HaF8icZUIdnY3qSZ7p.png",
                'file_path' => "what_we_sell/detail/19/5/XZeGVO3HsWHzyGfARombF8HaF8icZUIdnY3qSZ7p.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/5/XZeGVO3HsWHzyGfARombF8HaF8icZUIdnY3qSZ7p.png",
                'order' => 5,
            ],
            [
                'id' => 138,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU LASCOMBES, 2005",
                'description' => "$478 SGD",
                'file_name' => "uIBVKKalROGjb99X964ajXHyU7R2aFLptFIBk1FH.png",
                'file_path' => "what_we_sell/detail/19/6/uIBVKKalROGjb99X964ajXHyU7R2aFLptFIBk1FH.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/6/uIBVKKalROGjb99X964ajXHyU7R2aFLptFIBk1FH.png",
                'order' => 6,
            ],
            [
                'id' => 139,
                'what_we_sell_id' => 12,
                'title' => "TWO BOTTLES OF CHATEAU SOUTARD, 1995",
                'description' => "$239 SGD",
                'file_name' => "GlbgZI46xXFvgTxOnF05rXAU9XUp3fNjqtlnXCHQ.png",
                'file_path' => "what_we_sell/detail/19/7/GlbgZI46xXFvgTxOnF05rXAU9XUp3fNjqtlnXCHQ.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/7/GlbgZI46xXFvgTxOnF05rXAU9XUp3fNjqtlnXCHQ.png",
                'order' => 7,
            ],
            [
                'id' => 140,
                'what_we_sell_id' => 12,
                'title' => "A VINTAGE BOTTLE OF JOHNNIE WALKER 'SWING'",
                'description' => "$48 SGD",
                'file_name' => "SB84vVNjYeBIA5lBU4Q16lIvV3S9f92KukW8EtZd.png",
                'file_path' => "what_we_sell/detail/19/8/SB84vVNjYeBIA5lBU4Q16lIvV3S9f92KukW8EtZd.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/8/SB84vVNjYeBIA5lBU4Q16lIvV3S9f92KukW8EtZd.png",
                'order' => 8,
            ],
            [
                'id' => 141,
                'what_we_sell_id' => 12,
                'title' => "A MACALLAN BOTTLE OF FINE OAK SCOTCH WHISKY, 25 YEARS OLD",
                'description' => "$1,195 SGD",
                'file_name' => "yW4mDmH81B81RrT2VkAkI8r6aJlFnH5SJ75krN1u.png",
                'file_path' => "what_we_sell/detail/19/9/yW4mDmH81B81RrT2VkAkI8r6aJlFnH5SJ75krN1u.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/9/yW4mDmH81B81RrT2VkAkI8r6aJlFnH5SJ75krN1u.png",
                'order' => 9,
            ],
            [
                'id' => 142,
                'what_we_sell_id' => 12,
                'title' => "A 4.5L BOTTLE OF CHIVAS REGAL, 12 YEAR OLD",
                'description' => "$215 SGD",
                'file_name' => "R0ylSGjvCWtr63JcYvd37J9ftRK23TsUcj7pPf7H.png",
                'file_path' => "what_we_sell/detail/19/10/R0ylSGjvCWtr63JcYvd37J9ftRK23TsUcj7pPf7H.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/10/R0ylSGjvCWtr63JcYvd37J9ftRK23TsUcj7pPf7H.png",
                'order' => 10,
            ],
            [
                'id' => 143,
                'what_we_sell_id' => 12,
                'title' => "TWO VINTAGE BOTTLES OF CHIVAS REGAL",
                'description' => "$119 SGD",
                'file_name' => "1EeEBZZ89IohX0N1eCJBCiOb1Ziek7ioL8qaw8aX.png",
                'file_path' => "what_we_sell/detail/19/11/1EeEBZZ89IohX0N1eCJBCiOb1Ziek7ioL8qaw8aX.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/11/1EeEBZZ89IohX0N1eCJBCiOb1Ziek7ioL8qaw8aX.png",
                'order' => 11,
            ],
            [
                'id' => 144,
                'what_we_sell_id' => 12,
                'title' => "TWO VINTAGE BOTTLES OF JOHNNIE WALKER 'BLACK LABEL'",
                'description' => "$72 SGD",
                'file_name' => "BA0MF18CRgCQROaNgeEdbCcqrLCxYDTnXUKJUy7x.png",
                'file_path' => "what_we_sell/detail/19/12/BA0MF18CRgCQROaNgeEdbCcqrLCxYDTnXUKJUy7x.png",
                'full_path' => "https://s3.ap-southeast-1.amazonaws.com/staging.hotlotz.com/public/what_we_sell/detail/19/12/BA0MF18CRgCQROaNgeEdbCcqrLCxYDTnXUKJUy7x.png",
                'order' => 12,
            ],
        ];

        if (count($rows) > 0) {
            Seed::insertData(WhatWeSellHighlight::class, $rows);
        }
    }
}